import express from "express";
// @ts-expect-error - dist/index.cjs is generated by the build step and intentionally has no declaration file.
import * as runtime from "./dist/index.cjs";

void express;

export default (runtime as any).app;
