export const sixKalimas = [
  {
    number: 1,
    nameAr: "اَوَّل کَلِمَہ طَیِّب",
    nameEn: "First Kalima (Tayyab)",
    arabic: "لَآ اِلٰهَ اِلَّا اللّٰهُ مُحَمَّدٌ رَّسُوْلُ اللّٰهِ",
    transliteration: "Lā ilāha illallāhu Muḥammadur Rasūlullāh",
    translation: "There is no god but Allah, Muhammad is the Messenger of Allah.",
  },
  {
    number: 2,
    nameAr: "دُوسْرَا کَلِمَہ شَہَادَت",
    nameEn: "Second Kalima (Shahadat)",
    arabic: "اَشْهَدُ اَنْ لَّآ اِلٰهَ اِلَّا اللّٰهُ وَحْدَهٗ لَا شَرِيْكَ لَهٗ وَاَشْهَدُ اَنَّ مُحَمَّدًا عَبْدُهٗ وَرَسُوْلُهٗ",
    transliteration: "Ashhadu allā ilāha illallāhu waḥdahū lā sharīka lahū wa ashhadu anna Muḥammadan ʿabduhū wa rasūluhū",
    translation: "I bear witness that there is no god but Allah, He is One, He has no partner, and I bear witness that Muhammad is His servant and His Messenger.",
  },
  {
    number: 3,
    nameAr: "تِیسْرَا کَلِمَہ تَمْجِید",
    nameEn: "Third Kalima (Tamjeed)",
    arabic: "سُبْحَانَ اللّٰهِ وَالْحَمْدُ لِلّٰهِ وَلَآ اِلٰهَ اِلَّا اللّٰهُ وَاللّٰهُ اَكْبَرُ وَلَا حَوْلَ وَلَا قُوَّةَ اِلَّا بِاللّٰهِ الْعَلِيِّ الْعَظِيْمِ",
    transliteration: "Subḥānallāhi wal-ḥamdu lillāhi wa lā ilāha illallāhu wallāhu akbar, wa lā ḥawla wa lā quwwata illā billāhil ʿaliyyil ʿaẓīm",
    translation: "Glory be to Allah, all praise is for Allah, there is no god but Allah, Allah is the Greatest. There is no power or strength except with Allah, the Most High, the Most Great.",
  },
  {
    number: 4,
    nameAr: "چَوتھَا کَلِمَہ تَوحِید",
    nameEn: "Fourth Kalima (Tauheed)",
    arabic: "لَآ اِلٰهَ اِلَّا اللّٰهُ وَحْدَهٗ لَا شَرِيْكَ لَهٗ لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ يُحْيِيْ وَيُمِيْتُ وَهُوَ حَيٌّ لَا يَمُوْتُ اَبَدًا اَبَدًا ذُو الْجَلَالِ وَالْاِكْرَامِ بِيَدِهِ الْخَيْرُ وَهُوَ عَلٰى كُلِّ شَيْءٍ قَدِيْرٌ",
    transliteration: "Lā ilāha illallāhu waḥdahū lā sharīka lahū, lahul mulku wa lahul ḥamdu, yuḥyī wa yumītu wa huwa ḥayyun lā yamūtu abadan abadan, dhul-jalāli wal-ikrāmi biyadihil khayr, wa huwa ʿalā kulli shay'in qadīr",
    translation: "There is no god but Allah. He is One. He has no partner. His is the Kingdom and for Him is all praise. He gives life and causes death. And He is alive, He will never die. Owner of Majesty and Honour, in His hand is all goodness, and He has power over everything.",
  },
  {
    number: 5,
    nameAr: "پَانچْوَاں کَلِمَہ اِسْتِغْفَار",
    nameEn: "Fifth Kalima (Istighfar)",
    arabic: "اَسْتَغْفِرُ اللّٰهَ رَبِّيْ مِنْ كُلِّ ذَنْبٍ اَذْنَبْتُهٗ عَمَدًا اَوْ خَطَاً سِرًّا اَوْ عَلَانِيَةً وَاَتُوْبُ اِلَيْهِ مِنَ الذَّنْبِ الَّذِيْ اَعْلَمُ وَمِنَ الذَّنْبِ الَّذِيْ لَآ اَعْلَمُ اِنَّكَ اَنْتَ عَلَّامُ الْغُيُوْبِ وَسَتَّارُ الْعُيُوْبِ وَغَفَّارُ الذُّنُوْبِ وَلَا حَوْلَ وَلَا قُوَّةَ اِلَّا بِاللّٰهِ الْعَلِيِّ الْعَظِيْمِ",
    transliteration: "Astaghfirullāha rabbī min kulli dhanbin adhnabtuhu ʿamadan aw khaṭā'an, sirran aw ʿalāniyatan, wa atūbu ilayhi minadh-dhanbil-ladhī aʿlamu wa minadh-dhanbil-ladhī lā aʿlamu, innaka anta ʿallāmul-ghuyūbi wa sattārul-ʿuyūbi wa ghaffārudh-dhunūbi, wa lā ḥawla wa lā quwwata illā billāhil-ʿaliyyil-ʿaẓīm",
    translation: "I seek forgiveness from Allah, who is my Lord, from every sin I committed knowingly or unknowingly, secretly or openly. And I repent to Him from the sin that I know and from the sin that I do not know. Certainly You (O Allah), You are the Knower of the hidden things, the Concealer of mistakes, and the Forgiver of sins. And there is no power and no strength except with Allah, the Most High, the Most Great.",
  },
  {
    number: 6,
    nameAr: "چھٹا کَلِمَہ رَدِّ کُفْر",
    nameEn: "Sixth Kalima (Radd-e-Kufr)",
    arabic: "اَللّٰهُمَّ اِنِّيْ اَعُوْذُ بِكَ مِنْ اَنْ اُشْرِكَ بِكَ شَيْئًا وَّاَنَا اَعْلَمُ بِهٖ وَاَسْتَغْفِرُكَ لِمَا لَآ اَعْلَمُ بِهٖ تُبْتُ عَنْهُ وَتَبَرَّاْتُ مِنَ الْكُفْرِ وَالشِّرْكِ وَالْكِذْبِ وَالْغِيْبَةِ وَالْبِدْعَةِ وَالنَّمِيْمَةِ وَالْفَوَاحِشِ وَالْبُهْتَانِ وَالْمَعَاصِيْ كُلِّهَا وَاَسْلَمْتُ وَاَقُوْلُ لَآ اِلٰهَ اِلَّا اللّٰهُ مُحَمَّدٌ رَّسُوْلُ اللّٰهِ",
    transliteration: "Allāhumma innī aʿūdhu bika min an ushrika bika shay'an wa ana aʿlamu bihī wa astaghfiruka limā lā aʿlamu bihī, tubtu ʿanhu wa tabarrā'tu minal-kufri wash-shirki wal-kidhibi wal-ghībati wal-bidʿati wan-namīmati wal-fawāḥishi wal-buhtāni wal-maʿāṣī kullihā wa aslamtu wa aqūlu lā ilāha illallāhu Muḥammadur Rasūlullāh",
    translation: "O Allah, I seek refuge in You from knowingly associating any partner with You, and I seek Your forgiveness from that which I do not know. I repent from it, and I free myself from disbelief, polytheism, lying, backbiting, innovation, tale-carrying, indecency, slander, and all sins. I submit to Your will and I say: There is no god but Allah, Muhammad is the Messenger of Allah.",
  },
];

export const noraniQaidaLessons = [
  {
    number: 1,
    nameAr: "حُرُوْفِ مُفْرَدَات",
    nameEn: "Single Letters (Huroof Mufradaat)",
    content: "اَ بَ تَ ثَ جَ حَ خَ دَ ذَ رَ زَ سَ شَ صَ ضَ طَ ظَ عَ غَ فَ قَ كَ لَ مَ نَ وَ هَ يَ",
  },
  {
    number: 2,
    nameAr: "حُرُوْفِ مُرَکَّبَات",
    nameEn: "Combined Letters (Huroof Murakkabaat)",
    content: "بَا تَا ثَا جِيْمْ حَا خَا دَالْ ذَالْ رَا زَا سِيْنْ شِيْنْ صَادْ ضَادْ طَا ظَا عَيْنْ غَيْنْ فَا قَافْ كَافْ لَامْ مِيْمْ نُوْنْ وَاوْ هَا يَا",
  },
  {
    number: 3,
    nameAr: "حَرَکَات",
    nameEn: "Vowels (Harakaat)",
    content: "بَ بِ بُ — تَ تِ تُ — ثَ ثِ ثُ — جَ جِ جُ — حَ حِ حُ — خَ خِ خُ — دَ دِ دُ — ذَ ذِ ذُ — رَ رِ رُ — زَ زِ زُ — سَ سِ سُ — شَ شِ شُ",
  },
  {
    number: 4,
    nameAr: "تَنْوِیْن",
    nameEn: "Tanween",
    content: "بًا بٍ بٌ — تًا تٍ تٌ — ثًا ثٍ ثٌ — جًا جٍ جٌ — حًا حٍ حٌ — خًا خٍ خٌ — دًا دٍ دٌ — ذًا ذٍ ذٌ",
  },
  {
    number: 5,
    nameAr: "حُرُوْفِ مَدَّہ",
    nameEn: "Madd Letters",
    content: "بَا بِيْ بُوْ — تَا تِيْ تُوْ — ثَا ثِيْ ثُوْ — جَا جِيْ جُوْ — حَا حِيْ حُوْ — خَا خِيْ خُوْ",
  },
  {
    number: 6,
    nameAr: "سُکُوْن",
    nameEn: "Sukoon",
    content: "اَبْ اِبْ اُبْ — اَتْ اِتْ اُتْ — اَثْ اِثْ اُثْ — اَجْ اِجْ اُجْ — اَحْ اِحْ اُحْ — اَخْ اِخْ اُخْ",
  },
  {
    number: 7,
    nameAr: "تَشْدِیْد",
    nameEn: "Tashdeed",
    content: "اَبَّ اِبَّ اُبَّ — اَتَّ اِتَّ اُتَّ — اَثَّ اِثَّ اُثَّ — اَجَّ اِجَّ اُجَّ — اَحَّ اِحَّ اُحَّ — اَخَّ اِخَّ اُخَّ",
  },
];

export const imanAndNiyyat = [
  {
    nameAr: "صِفَتِ اِیْمَانِ مُجْمَل",
    nameEn: "Iman-e-Mujmal (Brief Declaration of Faith)",
    arabic: "اٰمَنْتُ بِاللّٰهِ كَمَا هُوَ بِاَسْمَآئِهٖ وَصِفَاتِهٖ وَقَبِلْتُ جَمِيْعَ اَحْكَامِهٖ اِقْرَارٌۢ بِالِّسَانِ وَتَصْدِيْقٌۢ بِالْقَلْبِ",
    transliteration: "Āmantu billāhi kamā huwa bi-asmā'ihī wa ṣifātihī wa qabiltu jamīʿa aḥkāmihī iqrārun bil-lisāni wa taṣdīqun bil-qalb",
    translation: "I believe in Allah as He is, with all His names and attributes, and I accept all His commands. Acknowledgment with the tongue and affirmation with the heart.",
  },
  {
    nameAr: "صِفَتِ اِیْمَانِ مُفَصَّل",
    nameEn: "Iman-e-Mufassal (Detailed Declaration of Faith)",
    arabic: "اٰمَنْتُ بِاللّٰهِ وَمَلٰٓئِكَتِهٖ وَكُتُبِهٖ وَرُسُلِهٖ وَالْيَوْمِ الْاٰخِرِ وَالْقَدْرِ خَيْرِهٖ وَشَرِّهٖ مِنَ اللّٰهِ تَعَالٰى وَالْبَعْثِ بَعْدَ الْمَوْتِ",
    transliteration: "Āmantu billāhi wa malā'ikatihī wa kutubihī wa rusulihī wal-yawmil-ākhiri wal-qadri khayrihī wa sharrihī minallāhi taʿālā wal-baʿthi baʿdal-mawt",
    translation: "I believe in Allah, His Angels, His Books, His Messengers, the Last Day, and that all good and bad destiny is from Allah the Most High, and in the resurrection after death.",
  },
  {
    nameAr: "رَوْزَہ رَکْھنَے کِی نِیَّت",
    nameEn: "Niyyat for Fasting (Roza)",
    arabic: "وَبِصَوْمِ غَدٍ نَوَيْتُ مِنْ شَهْرِ رَمَضَانَ",
    transliteration: "Wa biṣawmi ghadin nawaitu min shahri Ramaḍān",
    translation: "I intend to fast tomorrow in the month of Ramadan.",
  },
  {
    nameAr: "اِفْطَار کِی نِیَّت",
    nameEn: "Dua for Breaking Fast (Iftar)",
    arabic: "اَللّٰهُمَّ لَكَ صُمْتُ وَبِكَ اٰمَنْتُ وَعَلَيْكَ تَوَكَّلْتُ وَعَلٰى رِزْقِكَ اَفْطَرْتُ",
    transliteration: "Allāhumma laka ṣumtu wa bika āmantu wa ʿalayka tawakkaltu wa ʿalā rizqika afṭart",
    translation: "O Allah, I fasted for You, I believe in You, I put my trust in You, and I break my fast with Your sustenance.",
  },
  {
    nameAr: "تَسْبِیْحِ تَرَاوِیْح",
    nameEn: "Tasbeeh of Taraweeh",
    arabic: "سُبْحَانَ الْمَلِكِ الْقُدُّوْسِ سُبْحَانَ ذِي الْمُلْكِ وَالْمَلَكُوْتِ سُبْحَانَ ذِي الْعِزَّةِ وَالْعَظَمَةِ وَالْهَيْبَةِ وَالْقُدْرَةِ وَالْكِبْرِيَاءِ وَالْجَبَرُوْتِ سُبْحَانَ الْمَلِكِ الْحَيِّ الَّذِيْ لَا يَنَامُ وَلَا يَمُوْتُ سُبُّوْحٌ قُدُّوْسٌ رَبُّنَا وَرَبُّ الْمَلَائِكَةِ وَالرُّوْحِ اَللّٰهُمَّ اَجِرْنَا مِنَ النَّارِ بِرَحْمَتِكَ يَا مُجِيْرُ يَا مُجِيْرُ يَا مُجِيْرُ",
    transliteration: "Subḥānal-Malikil-Quddūs, Subḥāna dhil-Mulki wal-Malakūt, Subḥāna dhil-ʿIzzati wal-ʿAẓamati wal-Haybati wal-Qudrati wal-Kibriyā'i wal-Jabarūt, Subḥānal-Malikil-Ḥayyil-ladhī lā yanāmu wa lā yamūt, Subbūḥun Quddūsun Rabbunā wa Rabbul-Malā'ikati war-Rūḥ. Allāhumma ajirnā minan-Nāri bi-raḥmatika yā Mujīru yā Mujīru yā Mujīr",
    translation: "Glory be to the Sovereign, the Most Holy. Glory be to the Owner of the Kingdom and the Heavenly Realm. Glory be to the Owner of Honour, Greatness, Awe, Power, Pride, and Might. Glory be to the Sovereign, the Ever-Living who never sleeps and never dies. Most Glorious, Most Holy, our Lord and Lord of the Angels and the Spirit. O Allah, save us from the Fire by Your mercy, O Protector, O Protector, O Protector.",
  },
  {
    nameAr: "دُعَاءِ رَمَضَان شَرِیف",
    nameEn: "Dua for Ramadan (Laylatul Qadr)",
    arabic: "اَللّٰهُمَّ اِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنَّا يَا غَفُوْرُ",
    transliteration: "Allāhumma innaka ʿafuwwun tuḥibbul-ʿafwa faʿfu ʿannā yā Ghafūr",
    translation: "O Allah, You are the One who pardons, You love to pardon, so pardon us, O Most Forgiving.",
  },
  {
    nameAr: "نِیَّتِ نَمَازِ جَنَازَہ",
    nameEn: "Niyyat for Janaza Prayer",
    arabic: "نَوَيْتُ اَنْ اُؤَدِّيَ لِلّٰهِ تَعَالٰى اَرْبَعَ تَكْبِيْرَاتِ الصَّلٰوةِ الْجَنَازَةِ الثَّنَاءُ لِلّٰهِ تَعَالٰى وَالدُّعَاءُ لِهٰذَا الْمَيِّتِ اِقْتَدَيْتُ بِهٰذَا الْاِمَامِ مُتَوَجِّهًا اِلٰى جِهَةِ الْكَعْبَةِ الشَّرِيْفَةِ اَللّٰهُ اَكْبَرُ",
    transliteration: "Nawaitu an u'addiya lillāhi taʿālā arbaʿa takbīrātiṣ-ṣalātil-janāzati, ath-thanā'u lillāhi taʿālā wad-duʿā'u li-hādhal-mayyit, iqtadaytu bi-hādhal-imāmi mutawajjihan ilā jihatil-Kaʿbatish-Sharīfah. Allāhu Akbar",
    translation: "I intend to offer for Allah four Takbirs of Janaza prayer, praise for Allah and supplication for this deceased, following this Imam, facing the Holy Ka'bah. Allah is the Greatest.",
  },
  {
    nameAr: "ثَنَاء",
    nameEn: "Thana (Opening Praise in Janaza)",
    arabic: "سُبْحَانَكَ اللّٰهُمَّ وَبِحَمْدِكَ وَتَبَارَكَ اسْمُكَ وَتَعَالٰى جَدُّكَ وَجَلَّ ثَنَاؤُكَ وَلَا اِلٰهَ غَيْرُكَ",
    transliteration: "Subḥānakallāhumma wa biḥamdika wa tabārakasmuka wa taʿālā jadduka wa jalla thanā'uka wa lā ilāha ghayruk",
    translation: "Glory be to You, O Allah, and praise be to You. Blessed is Your name and exalted is Your majesty and glorious is Your praise. There is no god but You.",
  },
  {
    nameAr: "دُرُوْدِ اِبْرَاہِیْم",
    nameEn: "Durood-e-Ibrahim (Salawat)",
    arabic: "اَللّٰهُمَّ صَلِّ عَلٰى مُحَمَّدٍ وَّعَلٰى اٰلِ مُحَمَّدٍ كَمَا صَلَّيْتَ وَسَلَّمْتَ وَبَارَكْتَ وَرَحِمْتَ وَتَرَحَّمْتَ عَلٰى اِبْرَاهِيْمَ وَعَلٰى اٰلِ اِبْرَاهِيْمَ اِنَّكَ حَمِيْدٌ مَّجِيْدٌ",
    transliteration: "Allāhumma ṣalli ʿalā Muḥammadin wa ʿalā āli Muḥammad, kamā ṣallayta wa sallamta wa bārakta wa raḥimta wa taraḥḥamta ʿalā Ibrāhīma wa ʿalā āli Ibrāhīm, innaka Ḥamīdun Majīd",
    translation: "O Allah, send blessings upon Muhammad and upon the family of Muhammad, as You sent blessings, peace, grace, mercy and compassion upon Ibrahim and upon the family of Ibrahim. Indeed, You are Praiseworthy, Glorious.",
  },
  {
    nameAr: "دُعَاءِ جَنَازَہ (بَالِغ)",
    nameEn: "Janaza Dua for Adult",
    arabic: "اَللّٰهُمَّ اغْفِرْ لِحَيِّنَا وَمَيِّتِنَا وَشَاهِدِنَا وَغَائِبِنَا وَصَغِيْرِنَا وَكَبِيْرِنَا وَذَكَرِنَا وَاُنْثَانَا اَللّٰهُمَّ مَنْ اَحْيَيْتَهٗ مِنَّا فَاَحْيِهٖ عَلَى الْاِسْلَامِ وَمَنْ تَوَفَّيْتَهٗ مِنَّا فَتَوَفَّهٗ عَلَى الْاِيْمَانِ اَللّٰهُ اَكْبَرُ",
    transliteration: "Allāhummagh-fir li-ḥayyinā wa mayyitinā wa shāhidinā wa ghā'ibinā wa ṣaghīrinā wa kabīrinā wa dhakarinā wa unthānā. Allāhumma man aḥyaytahu minnā fa-aḥyihī ʿalal-Islām, wa man tawaffaytahu minnā fatawaffahu ʿalal-Īmān. Allāhu Akbar",
    translation: "O Allah, forgive our living and our dead, those present and those absent, our young and our old, our males and our females. O Allah, whomsoever among us You keep alive, let them live upon Islam, and whomsoever You take from us, take them upon faith. Allah is the Greatest.",
  },
  {
    nameAr: "دُعَاءِ جَنَازَہ لَڑکَے کَا",
    nameEn: "Janaza Dua for Boy Child",
    arabic: "اَللّٰهُمَّ اجْعَلْهُ لَنَا فَرَطًا وَاجْعَلْهُ لَنَا اَجْرًا وَذُخْرًا وَاجْعَلْهُ لَنَا شَافِعًا وَمُشَفَّعًا",
    transliteration: "Allāhummaj-ʿalhu lanā faraṭan waj-ʿalhu lanā ajran wa dhukhran waj-ʿalhu lanā shāfiʿan wa mushaffaʿā",
    translation: "O Allah, make him a forerunner for us, and make him a reward and a treasure for us, and make him an intercessor for us whose intercession is accepted.",
  },
  {
    nameAr: "دُعَاءِ جَنَازَہ لَڑکِی کَا",
    nameEn: "Janaza Dua for Girl Child",
    arabic: "اَللّٰهُمَّ اجْعَلْهَا لَنَا فَرَطًا وَاجْعَلْهَا لَنَا اَجْرًا وَذُخْرًا وَاجْعَلْهَا لَنَا شَافِعَةً وَمُشَفَّعَةً",
    transliteration: "Allāhummaj-ʿalhā lanā faraṭan waj-ʿalhā lanā ajran wa dhukhran waj-ʿalhā lanā shāfiʿatan wa mushaffaʿah",
    translation: "O Allah, make her a forerunner for us, and make her a reward and a treasure for us, and make her an intercessor for us whose intercession is accepted.",
  },
];

export const masnoonDuas = [
  {
    number: 1,
    nameAr: "سُوْرَج نِکْلَے تَوْ یَہ پَڑھَے",
    nameEn: "Dua After Sunrise",
    arabic: "اَلْحَمْدُ لِلّٰهِ الَّذِيْ اَقَالَنَا يَوْمَنَا هٰذَا وَلَمْ يُهْلِكْنَا بِذُنُوْبِنَا",
    translation: "All praise is for Allah who gave us this day and did not destroy us because of our sins.",
  },
  {
    number: 2,
    nameAr: "شَام کَوْ یَہ پَڑھَے",
    nameEn: "Dua for Evening",
    arabic: "اَللّٰهُمَّ بِكَ اَمْسَيْنَا وَبِكَ اَصْبَحْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوْتُ وَاِلَيْكَ النُّشُوْرُ",
    translation: "O Allah, by You we enter the evening and by You we enter the morning, by You we live and by You we die, and to You is the resurrection.",
  },
  {
    number: 3,
    nameAr: "صُبْح اَوْر شَام کِی اَیْک خَاص دُعَاء",
    nameEn: "Special Morning & Evening Dua (3 times)",
    arabic: "بِسْمِ اللّٰهِ الَّذِيْ لَا يَضُرُّ مَعَ اسْمِهٖ شَيْءٌ فِي الْاَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيْعُ الْعَلِيْمُ",
    translation: "In the name of Allah, with whose name nothing can cause harm on earth or in the heavens, and He is the All-Hearing, the All-Knowing.",
  },
  {
    number: 4,
    nameAr: "سَوْتَے وَقْت پَڑھنَے کِی چِیزَیں (۱)",
    nameEn: "Before Sleep (1) - 3 times",
    arabic: "اَللّٰهُمَّ قِنِيْ عَذَابَكَ يَوْمَ تَبْعَثُ عِبَادَكَ",
    translation: "O Allah, save me from Your punishment on the Day You resurrect Your servants.",
  },
  {
    number: 5,
    nameAr: "سَوْتَے وَقْت یَہ بِھی پَڑھَے (۲)",
    nameEn: "Before Sleep (2) - With Tasbeeh",
    arabic: "اَللّٰهُمَّ بِاسْمِكَ اَمُوْتُ وَاَحْيَا\n\nسُبْحَانَ اللّٰهِ ۳۳ بَار · اَلْحَمْدُ لِلّٰهِ ۳۳ بَار · اَللّٰهُ اَكْبَرُ ۳۴ بَار",
    translation: "O Allah, in Your name I die and I live. Then recite SubhanAllah 33 times, Alhamdulillah 33 times, Allahu Akbar 34 times.",
  },
  {
    number: 6,
    nameAr: "جَبْ سَوْکَر اُٹھَے تَوْ یَہ دُعَاء پَڑھَے",
    nameEn: "Dua When Waking Up",
    arabic: "اَلْحَمْدُ لِلّٰهِ الَّذِيْ اَحْيَانَا بَعْدَ مَآ اَمَاتَنَا وَاِلَيْهِ النُّشُوْرُ",
    translation: "All praise is for Allah who gave us life after death, and to Him is the return.",
  },
  {
    number: 7,
    nameAr: "بَیْتُ الْخَلَاء جَانَے کِی دُعَاء",
    nameEn: "Dua Before Entering Toilet",
    arabic: "اَللّٰهُمَّ اِنِّيْ اَعُوْذُبِكَ مِنَ الْخُبْثِ وَالْخَبَائِثِ",
    translation: "O Allah, I seek Your protection from evil male and female jinns.",
  },
  {
    number: 8,
    nameAr: "بَیْتُ الْخَلَاء سَے نِکْلَے تَوْ یَہ پَڑھَے",
    nameEn: "Dua After Leaving Toilet",
    arabic: "اَلْحَمْدُ لِلّٰهِ الَّذِيْ اَذْهَبَ عَنِّيَ الْاَذٰى وَعَافَانِيْ",
    translation: "All praise is for Allah who removed discomfort from me and gave me relief.",
  },
  {
    number: 9,
    nameAr: "جَبْ وُضُوْ کَرْنَا شُرُوْع کَرَے",
    nameEn: "Dua When Starting Wudhu",
    arabic: "بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيْمِ",
    translation: "In the name of Allah, the Most Gracious, the Most Merciful.",
  },
  {
    number: 10,
    nameAr: "جَبْ وُضُوْ کَر چُکَے تَوْ یَہ پَڑھَے",
    nameEn: "Dua After Completing Wudhu",
    arabic: "اَشْهَدُ اَنْ لَّا اِلٰهَ اِلَّا اللّٰهُ وَحْدَهٗ لَا شَرِيْكَ لَهٗ وَاَشْهَدُ اَنَّ مُحَمَّدًا عَبْدُهٗ وَرَسُوْلُهٗ اَللّٰهُمَّ اجْعَلْنِيْ مِنَ التَّوَّابِيْنَ وَاجْعَلْنِيْ مِنَ الْمُتَطَهِّرِيْنَ",
    translation: "I bear witness that there is no god but Allah alone, He has no partner, and I bear witness that Muhammad is His servant and Messenger. O Allah, make me among those who repent and make me among those who purify themselves.",
  },
  {
    number: 11,
    nameAr: "جَبْ مَسْجِد مَیں دَاخِل ہَوْ تَوْ یَہ دُعَاء پَڑھَے",
    nameEn: "Dua When Entering Masjid",
    arabic: "اَللّٰهُمَّ افْتَحْ لِيْ اَبْوَابَ رَحْمَتِكَ",
    translation: "O Allah, open the doors of Your mercy for me.",
  },
  {
    number: 12,
    nameAr: "مَسْجِد مَیں بَیْٹھَے بَیْٹھَے یَہ پَڑھَے",
    nameEn: "Dua While Waiting in Masjid",
    arabic: "سُبْحَانَ اللّٰهِ وَالْحَمْدُ لِلّٰهِ وَلَا اِلٰهَ اِلَّا اللّٰهُ وَاللّٰهُ اَكْبَرُ",
    translation: "Glory be to Allah, all praise is for Allah, there is no god but Allah, and Allah is the Greatest.",
  },
  {
    number: 13,
    nameAr: "جَبْ مَسْجِد سَے نِکْلَے تَوْ یَہ پَڑھَے",
    nameEn: "Dua When Leaving Masjid",
    arabic: "اَللّٰهُمَّ اِنِّيْ اَسْئَلُكَ مِنْ فَضْلِكَ",
    translation: "O Allah, I ask You from Your bounty.",
  },
  {
    number: 14,
    nameAr: "جَبْ اَذَان کِی آوَاز سُنَے",
    nameEn: "Reply During Adhaan",
    arabic: "لَا حَوْلَ وَلَا قُوَّةَ اِلَّا بِاللّٰهِ",
    translation: "There is no power and no strength except with Allah. (Say this when the Muazzin says Hayya Alas Salaah and Hayya Alal Falaah)",
  },
  {
    number: 15,
    nameAr: "اَذَان خَتْم ہَونَے کَے بَعْد دُرُوْد پَڑھ کَر یَہ پَڑھَے",
    nameEn: "Dua After Adhaan",
    arabic: "اَللّٰهُمَّ رَبَّ هٰذِهِ الدَّعْوَةِ التَّآمَّةِ وَالصَّلٰوةِ الْقَائِمَةِ اٰتِ مُحَمَّدًا الْوَسِيْلَةَ وَالْفَضِيْلَةَ وَابْعَثْهُ مَقَامًا مَّحْمُوْدًا الَّذِيْ وَعَدْتَّهٗ اِنَّكَ لَا تُخْلِفُ الْمِيْعَادَ",
    translation: "O Allah, Lord of this perfect call and the established prayer, grant Muhammad the intercession and the virtue, and raise him to the praiseworthy station which You have promised him. Indeed, You do not break Your promise.",
  },
  {
    number: 16,
    nameAr: "فَرْض نَمَاز کَا سَلَام پِھیْرْ کَر سَر پَر دَاہِنَا ہَاتِھ رَکْھ کَر یَہ پَڑھَے",
    nameEn: "After Farz Prayer - Hand on Head",
    arabic: "بِسْمِ اللّٰهِ الَّذِيْ لَا اِلٰهَ اِلَّا هُوَ الرَّحْمٰنُ الرَّحِيْمُ · اَللّٰهُمَّ اَذْهِبْ عَنِّيَ الْهَمَّ وَالْحُزْنَ",
    translation: "In the name of Allah, there is no god but He, the Most Gracious, the Most Merciful. O Allah, remove from me worry and grief.",
  },
  {
    number: 17,
    nameAr: "تِیْن بَار اَسْتَغْفِرُ اللّٰهَ کَہَے اَوْر یَہ دُعَاء پَڑھَے",
    nameEn: "After Farz Prayer - Istighfar & Salam",
    arabic: "اَللّٰهُمَّ اَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ تَبَارَكْتَ يَا ذَالْجَلَالِ وَالْاِكْرَامِ",
    translation: "Say Astaghfirullah 3 times, then: O Allah, You are Peace and from You is peace. Blessed are You, O Owner of Majesty and Honour.",
  },
  {
    number: 18,
    nameAr: "وِتْر پَڑھ کَر تِیْن مَرْتَبَہ یَہ پَڑھَے",
    nameEn: "After Witar Prayer (3 times)",
    arabic: "سُبْحَانَ الْمَلِكِ الْقُدُّوْسِ",
    translation: "Glory be to the Sovereign, the Most Holy. (Say 3 times after Witar, raise voice on the third time)",
  },
  {
    number: 19,
    nameAr: "نَمَاز فَجْر اَوْر نَمَاز مَغْرِب کَے بَعْد",
    nameEn: "7 Times After Fajr & Maghrib Prayer",
    arabic: "اَللّٰهُمَّ اَجِرْنِيْ مِنَ النَّارِ",
    translation: "O Allah, save me from the Hellfire. (Say 7 times before speaking to anyone after Fajr and Maghrib)",
  },
  {
    number: 20,
    nameAr: "گِھْر مَیں دَاخِل ہَوْ تَوْ یَہ دُعَاء پَڑھَے",
    nameEn: "Dua When Entering Home",
    arabic: "اَللّٰهُمَّ اِنِّيْ اَسْئَلُكَ خَيْرَ الْمَوْلِجِ وَخَيْرَ الْمَخْرَجِ بِسْمِ اللّٰهِ وَلَجْنَا وَعَلَى اللّٰهِ رَبِّنَا تَوَكَّلْنَا",
    translation: "O Allah, I ask You for a good entry and a good exit. In the name of Allah we enter and upon Allah our Lord we rely.",
  },
  {
    number: 21,
    nameAr: "بَازَار مَیں جَبْ جَائَے تَوْ یَہ دُعَاء پَڑھَے",
    nameEn: "Dua When Entering Shopping Area",
    arabic: "بِسْمِ اللّٰهِ اَللّٰهُمَّ اِنِّيْ اَسْئَلُكَ خَيْرَ هٰذِهِ السُّوْقِ وَخَيْرَ مَا فِيْهَا وَاَعُوْذُبِكَ مِنْ شَرِّهَا وَشَرِّ مَا فِيْهَا · اَللّٰهُمَّ اِنِّيْ اَعُوْذُبِكَ اَنْ اُصِيْبَ فِيْهَا يَمِيْنًا فَاجِرَةً اَوْ صَفْقَةً خَاسِرَةً",
    translation: "In the name of Allah. O Allah, I ask You for the good of this market and the good of what is in it, and I seek refuge from its evil. O Allah, I seek refuge that I may take a false oath or make a losing deal.",
  },
  {
    number: 22,
    nameAr: "جَبْ کِھَانَا شُرُوْع کَرَے تَوْ یَہ دُعَاء پَڑھَے",
    nameEn: "Dua Before Eating",
    arabic: "بِسْمِ اللّٰهِ وَعَلٰى بَرَكَةِ اللّٰهِ",
    translation: "In the name of Allah and with the blessings of Allah.",
  },
  {
    number: 23,
    nameAr: "شُرُوْع مَیں بِسْمِ اللّٰهِ بِھُوْل جَانَے پَر",
    nameEn: "If You Forgot Bismillah Before Eating",
    arabic: "بِسْمِ اللّٰهِ اَوَّلَهٗ وَاٰخِرَهٗ",
    translation: "In the name of Allah, at its beginning and at its end.",
  },
  {
    number: 24,
    nameAr: "جَبْ کِھَانَا کِھَا چُکَے تَوْ یَہ پَڑھَے",
    nameEn: "Dua After Eating",
    arabic: "اَلْحَمْدُ لِلّٰهِ الَّذِيْ اَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مِنَ الْمُسْلِمِيْنَ",
    translation: "All praise is for Allah who gave us food and drink and made us Muslims.",
  },
  {
    number: 25,
    nameAr: "دُوْدِھ پِی کَر یَہ دُعَاء پَڑھَے",
    nameEn: "Dua After Drinking Milk",
    arabic: "اَللّٰهُمَّ بَارِكْ لَنَا فِيْهِ وَزِدْنَا مِنْهُ",
    translation: "O Allah, bless us in it and give us more of it.",
  },
  {
    number: 26,
    nameAr: "جَبْ کِسِی کَے یَہَاں دَعْوَت کِھَائَے تَوْ یَہ پَڑھَے",
    nameEn: "Dua When Eating at Someone's Invitation",
    arabic: "اَللّٰهُمَّ اَطْعِمْ مَنْ اَطْعَمَنِيْ وَاسْقِ مَنْ سَقَانِيْ",
    translation: "O Allah, feed the one who fed me and give drink to the one who gave me drink.",
  },
  {
    number: 27,
    nameAr: "جَبْ مَیزْبَان کَے گِھْر سَے چَلْنَے لَگَے تَوْ یَہ دُعَاء پَڑھَے",
    nameEn: "Dua When Leaving Host's Home",
    arabic: "اَللّٰهُمَّ بَارِكْ لَهُمْ فِيْمَا رَزَقْتَهُمْ وَاغْفِرْلَهُمْ وَارْحَمْهُمْ",
    translation: "O Allah, bless them in what You have provided them, forgive them and have mercy on them.",
  },
  {
    number: 28,
    nameAr: "جَبْ رَوْزَہ اِفْطَار کَرَے تَوْ پَڑھَے",
    nameEn: "Dua for Breaking Fast (Iftar)",
    arabic: "اَللّٰهُمَّ اِنِّيْ لَكَ صُمْتُ وَبِكَ اٰمَنْتُ وَعَلَيْكَ تَوَكَّلْتُ وَعَلٰى رِزْقِكَ اَفْطَرْتُ",
    translation: "O Allah, I fasted for You, I believed in You, I put my trust in You, and I break my fast with Your sustenance.",
  },
  {
    number: 29,
    nameAr: "اِفْطَار کَے بَعْد یَہ پَڑھَے",
    nameEn: "Dua After Breaking Fast",
    arabic: "ذَهَبَ الظَّمَاُ وَابْتَلَّتِ الْعُرُوْقُ وَثَبَتَ الْاَجْرُ اِنْ شَاءَ اللّٰهُ",
    translation: "The thirst has gone, the veins are moistened, and the reward is confirmed, InshaAllah.",
  },
  {
    number: 30,
    nameAr: "اَگْر کِسِی کَے یَہَاں رَوْزَہ اِفْطَار کَرَے تَوْ یَہ پَڑھَے",
    nameEn: "Dua When Breaking Fast at Friend's Home",
    arabic: "اَفْطَرَ عِنْدَكُمُ الصَّائِمُوْنَ وَاَكَلَ طَعَامَكُمُ الْاَبْرَارُ وَصَلَّتْ عَلَيْكُمُ الْمَلَائِكَةُ",
    translation: "May the fasting people break their fast at your place, may the pious eat your food, and may the angels send blessings upon you.",
  },
  {
    number: 31,
    nameAr: "جَبْ کَپَڑَا اَپْنَے تَوْ یَہ پَڑھَے",
    nameEn: "Dua After Wearing Clothes",
    arabic: "اَلْحَمْدُ لِلّٰهِ الَّذِيْ كَسَانِيْ هٰذَا وَرَزَقَنِيْهِ مِنْ غَيْرِ حَوْلٍ مِّنِّيْ وَلَا قُوَّةٍ",
    translation: "All praise is for Allah who clothed me with this and provided it for me without any effort or strength from me.",
  },
  {
    number: 32,
    nameAr: "جَبْ نَیَا کَپَڑَا اَپْنَے تَوْ کَہَے",
    nameEn: "Dua When Wearing New Clothes",
    arabic: "اَللّٰهُمَّ لَكَ الْحَمْدُ كَمَا كَسَوْتَنِيْهِ اَسْئَلُكَ خَيْرَهٗ وَخَيْرَ مَا صُنِعَ لَهٗ وَاَعُوْذُبِكَ مِنْ شَرِّهٖ وَشَرِّ مَا صُنِعَ لَهٗ",
    translation: "O Allah, all praise is Yours as You have clothed me. I ask You for its good and the good for which it was made, and I seek refuge from its evil and the evil for which it was made.",
  },
  {
    number: 33,
    nameAr: "جَبْ آئِینَے مَیں اَپْنَا چِہْرَہ دَیْکِھَے تَوْ یَہ پَڑھَے",
    nameEn: "Dua When Looking in Mirror",
    arabic: "اَللّٰهُمَّ اَنْتَ حَسَّنْتَ خَلْقِيْ فَحَسِّنْ خُلُقِيْ",
    translation: "O Allah, just as You made my appearance beautiful, make my character beautiful too.",
  },
  {
    number: 34,
    nameAr: "دُوْلِھَا کَوْ یُوْں مُبَارَکْبَاد دَیْوَے",
    nameEn: "Dua for the Groom (Wedding Congratulations)",
    arabic: "بَارَكَ اللّٰهُ لَكَ وَبَارَكَ عَلَيْكُمَا وَجَمَعَ بَيْنَكُمَا فِيْ خَيْرٍ",
    translation: "May Allah bless you, and may He bless you both, and may He unite you both in goodness.",
  },
  {
    number: 35,
    nameAr: "شَبِ قَدْر مَیں یُوْں دُعَاء مَانْگَے",
    nameEn: "Dua for Laylatul Qadr (Night of Power)",
    arabic: "اَللّٰهُمَّ اِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّيْ",
    translation: "O Allah, You are the Pardoner, You love to pardon, so pardon me.",
  },
  {
    number: 36,
    nameAr: "جَبْ نَیَا چَاند دَیْکِھَے تَوْ یَہ پَڑھَے",
    nameEn: "Dua When Seeing the New Moon",
    arabic: "اَللّٰهُمَّ اَهِلَّهٗ عَلَيْنَا بِالْيُمْنِ وَالْاِيْمَانِ وَالسَّلَامَةِ وَالْاِسْلَامِ وَالتَّوْفِيْقِ لِمَا تُحِبُّ وَتَرْضٰى رَبِّيْ وَرَبُّكَ اللّٰهُ",
    translation: "O Allah, bring this moon upon us with blessings, faith, safety, Islam, and the ability to do what You love and are pleased with. My Lord and your Lord is Allah.",
  },
  {
    number: 37,
    nameAr: "کِسِی مَرِیْض مُسْلِمَان کِی عِیَادَت کَوْ جَائَے",
    nameEn: "Dua When Visiting a Sick Person",
    arabic: "لَا بَأْسَ طَهُوْرٌ اِنْ شَاءَ اللّٰهُ",
    translation: "No worry, it is a purification (from sins), InshaAllah.",
  },
  {
    number: 38,
    nameAr: "جَبْ سَوَارِی پَر بَیْٹِھ جَائَے تَوْ یَہ پَڑھَے",
    nameEn: "Dua When Sitting in a Vehicle",
    arabic: "سُبْحَانَ الَّذِيْ سَخَّرَ لَنَا هٰذَا وَمَا كُنَّا لَهٗ مُقْرِنِيْنَ وَاِنَّا اِلٰى رَبِّنَا لَمُنْقَلِبُوْنَ",
    translation: "Glory be to Him who has subjected this to us, and we were not capable of doing that, and surely to our Lord we will return.",
  },
  {
    number: 39,
    nameAr: "کِسِی مَنْزِل (رَیْلْوَے اِسْٹَیْشَن، بَس اِسْٹَاپ) پَر اُتْرَے تَوْ",
    nameEn: "Dua When Reaching Any Place",
    arabic: "اَعُوْذُ بِكَلِمَاتِ اللّٰهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
    translation: "I seek refuge in the perfect words of Allah from the evil of what He has created.",
  },
  {
    number: 40,
    nameAr: "جَبْ قَبْرِسْتَان مَیں جَائَے تَوْ یَہ پَڑھَے",
    nameEn: "Dua When Visiting the Graveyard",
    arabic: "اَلسَّلَامُ عَلَيْكُمْ يَا اَهْلَ الْقُبُوْرِ يَغْفِرُ اللّٰهُ لَنَا وَلَكُمْ اَنْتُمْ سَلَفُنَا وَنَحْنُ بِالْاَثَرِ",
    translation: "Peace be upon you, O people of the graves. May Allah forgive us and you. You have gone before us, and we are following after you.",
  },
];

export const imanKaBiyan = [
  {
    number: 1,
    nameAr: "اِسْلَام کَے پَانْچ اَرْکَان",
    nameEn: "Five Pillars of Islam",
    arabic: "",
    content: "پیارے بچو! ہمارے پیارے رسول حضرت محمد مصطفیٰ ﷺ نے فرمایا ہے کہ اسلام کی بنیاد پانچ چیزوں پر رکھی گئی ہے۔\n\n☆ اول یہ گواہی دینا کہ اللہ کے سوا کوئی معبود نہیں اور حضرت محمد مصطفیٰ ﷺ اللہ کے رسول ہیں۔\n☆ دوسرے نماز قائم کرنا یعنی قاعدے کے مطابق پابندی سے نماز پڑھنا۔\n☆ تیسرے زکوٰۃ دینا۔\n☆ چوتھے حج کرنا۔\n☆ پانچویں رمضان شریف کے روزے رکھنا۔\n\nاللہ تنہا ہے اور بس وہی معبود ہے۔ اسکے علاوہ کوئی عبادت کے لائق نہیں اور حضرت محمد مصطفیٰ ﷺ اللہ کے سچے اور آخری رسول ہیں۔ ان دونوں باتوں کی گواہی دینے اور دل سے اقرار کرنے کو ایمان کہتے ہیں۔ کلمہ طیبہ اور کلمہ شہادت میں اسی کا اقرار ہے۔",
    translation: "Dear children! Our beloved Prophet Muhammad ﷺ said that Islam is built on five things:\n\n☆ First: To bear witness that there is no god but Allah and Muhammad ﷺ is the Messenger of Allah.\n☆ Second: To establish prayer (Salah) regularly.\n☆ Third: To give Zakat (charity).\n☆ Fourth: To perform Hajj (pilgrimage).\n☆ Fifth: To fast during Ramadan.\n\nAllah is One and He alone is worthy of worship. Muhammad ﷺ is His true and final Messenger. Bearing witness to these two things with the heart is called Iman (Faith).",
  },
  {
    number: 2,
    nameAr: "کَلِمَہ طَیِّبَہ یَا کَلِمَہ تَوْحِیْد",
    nameEn: "Kalima Tayyiba (Word of Purity)",
    arabic: "لَا اِلٰہَ اِلَّا اللّٰہُ مُحَمَّدٌ رَّسُوْلُ اللّٰہِ",
    content: "ترجمہ: کوئی معبود نہیں اللہ کے سوا اور حضرت محمد ﷺ اللہ کے رسول ہیں۔",
    translation: "There is no god but Allah, Muhammad is the Messenger of Allah.",
  },
  {
    number: 3,
    nameAr: "کَلِمَہ شَہَادَت",
    nameEn: "Kalima Shahadat (Word of Testimony)",
    arabic: "اَشْھَدُ اَنْ لَّا اِلٰہَ اِلَّا اللّٰہُ وَحْدَہٗ لَا شَرِیْکَ لَہٗ وَ اَشْھَدُ اَنَّ مُحَمَّدًا عَبْدُہٗ وَرَسُوْلُہٗ",
    content: "ترجمہ: میں گواہی دیتا ہوں کہ اللہ کے سوا کوئی معبود نہیں وہ تنہا ہے اس کا کوئی شریک نہیں اور گواہی دیتا ہوں کہ حضرت محمد ﷺ اسکے بندے اور رسول ہیں۔\n\nحضرت محمد مصطفیٰ ﷺ نے جو کچھ بھی بتایا اور فرمایا سب حق ہے اس کا ماننا لازم اور فرض ہے۔ آپ ﷺ نے جو غیب کی باتیں بتائی ہیں جیسے قیامت کا آنا، مرنے کے بعد زندہ ہونا، حساب و کتاب ہوکر جنت یا دوزخ میں جانا۔ قبر میں عذاب یا ثواب ہونا آسمانوں پر آپ ﷺ کا معراج میں جانا وغیرہ وغیرہ سب حق ہے۔ اللہ کی کتابوں اور اسکے فرشتوں اور تمام پیغمبروں پر ایمان لانا بھی فرض ہے۔ اسی کو ایمان مجمل اور ایمان مفصل میں بتایا ہے۔",
    translation: "I bear witness that there is no god but Allah, He is One, He has no partner, and I bear witness that Muhammad ﷺ is His servant and Messenger.\n\nEverything that Prophet Muhammad ﷺ told us is the truth and believing in it is obligatory. The unseen matters he informed us about — the Day of Judgement, life after death, accountability, Paradise and Hell, punishment or reward in the grave, his ascension (Mi'raj) to the heavens — all are true. Believing in Allah's books, His angels, and all prophets is also obligatory.",
  },
  {
    number: 4,
    nameAr: "اِیْمَان مُجْمَل",
    nameEn: "Iman Mujmal (Brief Declaration of Faith)",
    arabic: "اٰمَنْتُ بِاللّٰہِ کَمَا ھُوَ بِاَسْمَآئِہٖ وَ صِفَاتِہٖ وَقَبِلْتُ جَمِیْعَ اَحْکَامِہٖ اِقْرَارٌ بِاللِّسَانِ وَ تَصْدِیْقٌ بِالْقَلْبِ",
    content: "ترجمہ: ایمان لایا میں اللہ پر جیسا کہ وہ اپنے ناموں اور صفتوں کے ساتھ ہے اور میں نے اس کے تمام احکام قبول کئے۔",
    translation: "I believe in Allah as He is with His names and attributes, and I have accepted all His commandments — declaration by the tongue and confirmation by the heart.",
  },
  {
    number: 5,
    nameAr: "اِیْمَان مُفَصَّل",
    nameEn: "Iman Mufassal (Detailed Declaration of Faith)",
    arabic: "اٰمَنْتُ بِاللّٰہِ وَمَلٰئِکَتِہٖ وَکُتُبِہٖ وَ رُسُلِہٖ وَالْیَوْمِ الْاٰخِرِ وَالْقَدْرِ خَیْرِہٖ وَ شَرِّہٖ مِنَ اللّٰہِ تَعَالٰی وَالْبَعْثِ بَعْدَ الْمَوْتِ",
    content: "ترجمہ: ایمان لایا میں اللہ پر اور اسکے فرشتوں پر اور اسکی کتابوں پر اور اسکے رسولوں پر اور قیامت کے دن پر اور اس پر کہ اچھی اور بری تقدیر خدا تعالٰی کی طرف سے اور موت کے بعد اٹھائے جانے پر بھی میں ایمان لایا۔",
    translation: "I believe in Allah, His angels, His books, His messengers, the Last Day, and that all good and bad destiny is from Allah, and in the resurrection after death.",
  },
  {
    number: 6,
    nameAr: "کُفْر، شِرْک اَوْر نِفَاق",
    nameEn: "Kufr, Shirk and Nifaq (Disbelief, Polytheism, Hypocrisy)",
    arabic: "",
    content: "جو لوگ اللہ تعالٰی کو نہیں مانتے یا حضرت محمد ﷺ کو نبی و رسول تسلیم نہیں کرتے یا آپ ﷺ کو آخری نبی نہیں مانتے آپ ﷺ کے بعد کسی دوسرے کو بھی نبی سمجھتے ہیں یا جو لوگ قیامت کو نہیں مانتے یا اسلامی عقیدوں کا انکار کرتے ہیں یا اسلام کے فرضوں کو نہیں مانتے یا اسلام کی باتوں کا مذاق اڑاتے ہیں ایسے لوگ کافر ہیں۔\n\nاور جو لوگ اللہ کے علاوہ کسی کی عبادت کرتے ہیں جیسے ہندو لوگ بتوں کو پوجتے ہیں یا جو لوگ اللہ کیلئے اولاد مانتے ہیں ایسے لوگ مشرک ہیں۔\n\nجو لوگ دل سے مسلمان نہیں صرف ظاہری طور پر کہہ دیتے ہیں کہ ہم مسلمان ہیں ایسے لوگوں کو منافق کہتے ہیں۔\n\nکافر مشرک اور منافق کی بھی بخشش نہ ہوگی اور یہ لوگ ہمیشہ دوزخ کے عذاب میں رہیں گے۔ (اللہ ہم سب کو پناہ دے)",
    translation: "Those who do not believe in Allah, or do not accept Muhammad ﷺ as a Prophet, or do not accept him as the final Prophet, or deny the Day of Judgement, or reject Islamic beliefs, or mock Islam — such people are Kafir (disbelievers).\n\nThose who worship others besides Allah — such people are Mushrik (polytheists).\n\nThose who are not Muslim in their hearts but only claim to be Muslim outwardly — such people are called Munafiq (hypocrites).\n\nKafir, Mushrik and Munafiq will never be forgiven and will remain in the punishment of Hell forever. (May Allah protect us all)",
  },
];

export const wuzuKaBiyan = [
  {
    number: 1,
    nameAr: "طَہَارَت کَا بَیَان",
    nameEn: "Importance of Cleanliness (Taharat)",
    arabic: "اِنَّ اللّٰہَ یُحِبُّ التَّوَّابِیْنَ وَ یُحِبُّ الْمُتَطَہِّرِیْنَ",
    content: "طہارت یعنی پاکی کا اسلام میں بڑا دخل ہے۔ قرآن شریف میں ارشاد ہے:\n\nیعنی یقین جانو کہ اللہ تعالٰی خوب توبہ کرنے والوں کو اور اچھی طرح پاکی حاصل کرنے والوں کو دوست رکھتا ہے۔\n\nنماز صحیح ہونے کیلئے بدن، کپڑے اور جائے نماز کا پاک ہونا اور با وضو ہونا شرط ہے۔\n\nحدیث: فرمایا آقائے دو جہاں ﷺ نے کہ کوئی نماز بغیر پاکی کے قبول نہیں ہوتی اور کوئی صدقہ حرام مال سے قبول نہیں ہوتا۔",
    translation: "Indeed, Allah loves those who repent and loves those who purify themselves.\n\nCleanliness has great importance in Islam. For prayer to be valid, the body, clothes, and place of prayer must be clean, and one must have Wudhu.\n\nHadith: The Prophet ﷺ said that no prayer is accepted without cleanliness, and no charity from unlawful wealth is accepted.",
  },
  {
    number: 2,
    nameAr: "وُضُو کَے فَرَائِض",
    nameEn: "Obligations of Wudhu (4 Farz)",
    arabic: "",
    content: "وضو میں چار فرض ہیں:\n\n۱۔ پیشانی کے بالوں سے لے کر ٹھوڑی کے نیچے اور دونوں کانوں کی لوٹک منہ دھونا۔\n۲۔ دونوں ہاتھ کہنیوں سمیت دھونا۔\n۳۔ چوتھائی سر کا مسح کرنا۔\n۴۔ دونوں پاؤں ٹخنوں سمیت دھونا۔",
    translation: "There are four obligatory (Farz) acts in Wudhu:\n\n1. Washing the face from the hairline to below the chin, and from one earlobe to the other.\n2. Washing both hands including the elbows.\n3. Wiping (Masah) a quarter of the head.\n4. Washing both feet including the ankles.",
  },
  {
    number: 3,
    nameAr: "وُضُو کِی سُنَّتیں",
    nameEn: "Sunnah Acts of Wudhu",
    arabic: "",
    content: "☆ نیت کرنا۔\n☆ شروع میں بسم اللہ پڑھنا اور پہلے تین بار دونوں ہاتھ کلائی تک دھونا۔\n☆ پھر تین بار کلی کرنا اور مسواک کرنا۔\n☆ پھر تین بار ناک میں پانی ڈالنا۔\n☆ تین تین بار دھونا۔\n☆ سارے سر کا مسح کرنا۔\n☆ داڑھی اور انگلیوں کا خلال کرنا۔\n☆ لگاتار اس طرح دھونا کہ پہلا عضو خشک نہ ہونے پائے اور دوسرا عضو دھل جائے۔\n☆ ترتیب وار دھونا کہ پہلے منہ دھوئے پھر کہنیوں سمیت ہاتھ دھوئے پھر سر کا مسح کرے پھر پاؤں دھوئے۔\n\n(سنت چھوڑنے سے وضو تو ہو جاتا ہے مگر ثواب کم ملتا ہے)",
    translation: "Sunnah acts of Wudhu:\n\n☆ Making intention (Niyyat).\n☆ Saying Bismillah at the start and washing both hands up to the wrists three times.\n☆ Rinsing the mouth three times and using Miswak.\n☆ Sniffing water into the nose three times.\n☆ Washing each part three times.\n☆ Wiping the entire head.\n☆ Running fingers through the beard and between the fingers.\n☆ Washing continuously so the first part doesn't dry before the next is washed.\n☆ Washing in order: face first, then hands with elbows, then Masah of head, then feet.\n\n(If Sunnah acts are omitted, the Wudhu is still valid but less reward is earned)",
  },
  {
    number: 4,
    nameAr: "مُسْتَحَبَّاتِ وُضُو",
    nameEn: "Recommended Acts of Wudhu (Mustahabbat)",
    arabic: "",
    content: "☆ قبلہ رخ ہوکر بیٹھنا، مل کر دھونا۔\n☆ داہنی طرف سے شروع کرنا۔\n☆ بچا ہوا پانی کھڑے ہوکر پینا۔\n☆ دوسرے سے مدد نہ لینا۔\n\n(مستحب چھوٹ جانے سے وضو تو ہو جاتا ہے مگر مستحب کا جو ثواب ہے وہ نہیں ملتا اور مستحب کا درجہ سنت سے کم ہے۔)",
    translation: "Recommended acts:\n\n☆ Sitting facing the Qibla direction, rubbing while washing.\n☆ Starting from the right side.\n☆ Drinking leftover water while standing.\n☆ Not taking help from others.\n\n(If Mustahab acts are omitted, Wudhu is still valid but the reward of Mustahab is lost. Mustahab is a lower rank than Sunnah.)",
  },
  {
    number: 5,
    nameAr: "مَکْرُوْہَاتِ وُضُو",
    nameEn: "Disliked Acts During Wudhu (Makroohat)",
    arabic: "",
    content: "☆ ناپاک جگہ وضو کرنا۔\n☆ سیدھے ہاتھ سے ناک صاف کرنا۔\n☆ پانی زیادہ بہانا۔\n☆ وضو کرتے وقت دنیا کی باتیں کرنا۔\n☆ خلاف سنت وضو کرنا۔\n☆ زور سے چھینکے مارنا۔",
    translation: "Disliked (Makrooh) acts during Wudhu:\n\n☆ Performing Wudhu in an impure place.\n☆ Cleaning the nose with the right hand.\n☆ Wasting too much water.\n☆ Talking about worldly matters during Wudhu.\n☆ Performing Wudhu against the Sunnah method.\n☆ Sneezing forcefully.",
  },
  {
    number: 6,
    nameAr: "نَوَاقِضِ وُضُو",
    nameEn: "Things That Break Wudhu (Nawaqis)",
    arabic: "",
    content: "ان چیزوں سے وضو ٹوٹ جاتا ہے:\n\n☆ پاخانہ یا پیشاب کرنا یا ہوا خارج ہونا۔\n☆ خون یا پیپ نکل کر بہہ جانا۔\n☆ منہ بھر کر قے ہونا۔\n☆ ٹیک لگا کر یا لیٹ کر سو جانا۔\n☆ نشے میں مست یا بے ہوش ہو جانا۔\n☆ رکوع سجدہ والی نماز میں قہقہہ مار کر ہنسنا۔",
    translation: "These things break the Wudhu:\n\n☆ Using the toilet or passing gas.\n☆ Blood or pus flowing from a wound.\n☆ Vomiting a mouthful.\n☆ Sleeping while leaning or lying down.\n☆ Becoming intoxicated or unconscious.\n☆ Laughing loudly (Qahqaha) during a prayer that has Ruku and Sajdah.",
  },
  {
    number: 7,
    nameAr: "وُضُو کَا طَرِیْقَہ",
    nameEn: "Step-by-Step Method of Wudhu",
    arabic: "",
    content: "وضو کرنے کا طریقہ یہ ہے کہ:\n\n☆ پاک برتن میں پاک پانی لے کر پاک جگہ پر بیٹھو، اونچی جگہ ہو تو بہتر ہے تا کہ چھینٹے نہ آئیں قبلہ کی طرف منہ کر لو تو اور اچھا ہے۔\n☆ اور آستینیں کہنیوں سے اوپر تک چڑھا لو۔ پھر بسم اللہ پڑھو اور تین بار گٹوں تک دونوں ہاتھ دھوؤ۔\n☆ پھر تین بار کلی کرو اور مسواک کرو۔ مسواک نہ ہو تو انگلی سے دانت مل لو۔\n☆ پھر تین بار ناک میں پانی ڈال کر بائیں ہاتھ سے صاف کرو۔ ناک میں پانی ڈالنے کا مطلب یہ ہے کہ سانس کے ساتھ نرم جگہ تک پانی لے جائیں۔\n☆ پھر تین مرتبہ منہ دھوؤ۔ منہ پر پانی زور سے نہ مارو بلکہ آہستہ سے پیشانی پر پانی ڈال کر دھوؤ۔ پیشانی کے بالوں سے ٹھوڑی کے نیچے تک اور ادھر ادھر دونوں کانوں کی لوٹک منہ دھوؤ۔\n☆ پھر کہنیوں سمیت دونوں ہاتھ دھوؤ۔ پہلے داہنا ہاتھ تین بار پھر بایاں ہاتھ تین بار دھوؤ۔\n☆ پھر دونوں ہاتھ پانی سے تر کر کے سر کا مسح کرو۔ دونوں ہاتھوں کی انگلیاں برابر ملا کر پیشانی کے بالوں پر رکھ کر گدی تک لے جاؤ۔ پھر گدی سے دونوں ہاتھوں کی ہتھیلیوں کو کانوں کے پاس سے گذارتے کانوں کے دونوں سوراخوں میں شہادت کی انگلیاں داخل کرو اور انگوٹھوں سے کانوں کی پشت کا مسح کرو اور انگلیوں کی پشت سے گردن کا مسح کرو۔\n☆ پھر تین تین مرتبہ دونوں پاؤں ٹخنوں سمیت دھوؤ۔ پہلے داہنا پاؤں پھر بایاں پاؤں دھوؤ۔",
    translation: "Method of Wudhu:\n\n☆ Take clean water in a clean vessel and sit in a clean place, preferably elevated to avoid splashes. Face the Qibla if possible.\n☆ Roll up sleeves above the elbows. Say Bismillah and wash both hands up to the wrists three times.\n☆ Rinse the mouth three times and use Miswak. If no Miswak, rub teeth with fingers.\n☆ Sniff water into the nose three times and clean with the left hand. Water should reach the soft part of the nose.\n☆ Wash the face three times gently — from the hairline to below the chin and from earlobe to earlobe.\n☆ Wash both hands including elbows — right hand three times, then left hand three times.\n☆ Wet both hands and do Masah of the head — place fingers on the forehead hairline and move to the back of the head, then bring palms back along the sides. Insert index fingers into the ears, wipe behind the ears with thumbs, and wipe the back of the neck with the back of the fingers.\n☆ Wash both feet including ankles three times each — right foot first, then left foot.",
  },
  {
    number: 8,
    nameAr: "وُضُو کَے بَعْد کِی دُعَاء",
    nameEn: "Dua After Completing Wudhu",
    arabic: "اَشْھَدُ اَنْ لَّا اِلٰہَ اِلَّا اللّٰہُ وَ حْدَہٗ لَا شَرِیْکَ لَہٗ وَ اَشْھَدُ اَنَّ مُحَمَّدًا عَبْدُہٗ وَرَسُوْلُہٗ\nاَللّٰھُمَّ اجْعَلْنِیْ مِنَ التَّوَّابِیْنَ وَاجْعَلْنِیْ مِنَ الْمُتَطَہِّرِیْنَ",
    content: "ترجمہ: میں گواہی دیتا ہوں کہ اللہ کے سوا کوئی معبود نہیں وہ تنہا ہے اس کا کوئی شریک نہیں اور گواہی دیتا ہوں کہ حضرت محمد ﷺ اسکے بندے اور رسول ہیں۔ اے اللہ تو مجھے خوب زیادہ توبہ کرنے والوں میں اور خوب زیادہ پاکی حاصل کرنے والوں میں شامل فرما دے۔",
    translation: "I bear witness that there is no god but Allah, He is One, He has no partner, and I bear witness that Muhammad ﷺ is His servant and Messenger. O Allah, make me among those who repent greatly and those who purify themselves greatly.",
  },
];

export const ghusulKaBiyan = [
  {
    number: 1,
    nameAr: "غُسْل کَا طَرِیْقَہ",
    nameEn: "Method of Ghusl (Ritual Bath)",
    arabic: "",
    content: "☆ جب غسل کا ارادہ کرے تو پہلے استنجاء کرے اور کسی جگہ ظاہری ناپاکی لگی ہو تو اس کو دھو لیوے۔\n☆ پھر وضو کرے جیسا نماز کیلئے وضو کرتے ہیں۔ اگر پختہ جگہ ہو یا تختہ یا پتھر پر غسل کر رہا ہو تو پاؤں بھی ابھی دھو لیوے۔ اور اگر کچی جگہ میں غسل کر رہا ہو تو پورا غسل کرکے آخر میں پاؤں دھوئے۔\n☆ غسل کے وضو میں کلی کرتے ہوئے خوب خیال کر کے حلق تک پانی لے جائے اور منہ بھر کر کلی کرے۔ اگر روزہ نہ ہو تو غرارہ بھی کرے اور ناک میں جہاں تک نرم جگہ ہے وہاں تک سانس کے ساتھ پانی لے جائے۔\n☆ وضو کے بعد تھوڑا سا پانی لے کر سارے بدن پر مل لیوے۔\n☆ اسکے بعد تین بار سر پر پانی ڈالے پھر تین بار دائنے کاندھے پر پھر تین بار بائیں کاندھے پر پانی ڈالے اور ہر جگہ خیال کر کے پانی پہنچائے۔ بال برابر بھی جگہ سوکھی رہ جائے تو غسل نہ ہوگا۔\n\nمسئلہ: اگر غسل کے بعد معلوم ہو کہ فلاں جگہ سوکھی رہ گئی ہے تو خاص اسی جگہ کو دھو لیوے پھر سے پورا غسل دہرانے کی ضرورت نہیں۔",
    translation: "Method of Ghusl:\n\n☆ First perform Istinja and wash off any visible impurity.\n☆ Then perform Wudhu as you would for prayer. If on a solid surface, wash the feet now. If on soft ground, wash feet at the end.\n☆ During Ghusl Wudhu, gargle thoroughly reaching the throat. If not fasting, gargle deeply. Sniff water into the nose up to the soft part.\n☆ After Wudhu, rub a little water over the entire body.\n☆ Then pour water over the head three times, then right shoulder three times, then left shoulder three times. Ensure water reaches every part — if even a hair's breadth remains dry, the Ghusl is invalid.\n\nRuling: If after Ghusl you discover a spot remained dry, just wash that spot. There is no need to repeat the entire Ghusl.",
  },
  {
    number: 2,
    nameAr: "فَرَائِضِ غُسْل",
    nameEn: "Obligations of Ghusl (3 Farz)",
    arabic: "",
    content: "فرائض غسل تین ہیں:\n\n۱۔ خوب حلق تک پانی سے منہ بھر کر کلی کرنا۔\n۲۔ ناک میں سانس کے ساتھ پانی چڑھانا جہاں تک نرم جگہ ہے۔\n۳۔ تمام بدن پر ایک بار پانی بہانا۔",
    translation: "There are three obligatory (Farz) acts in Ghusl:\n\n1. Gargling thoroughly, filling the mouth with water reaching the throat.\n2. Sniffing water into the nose up to the soft part.\n3. Pouring water over the entire body at least once.",
  },
  {
    number: 3,
    nameAr: "غُسْل کِی سُنَّتیں",
    nameEn: "Sunnah Acts of Ghusl",
    arabic: "",
    content: "غسل کی سنتیں یہ ہیں:\n\n۱۔ غسل کی نیت کرنا۔\n۲۔ اولاً ظاہری ناپاکی دور کرنا اور استنجاء کرنا۔\n۳۔ پھر وضو کرنا۔\n۴۔ بدن کو ملنا۔\n۵۔ سارے بدن پر تین بار پانی بہانا۔",
    translation: "Sunnah acts of Ghusl:\n\n1. Making the intention (Niyyat) for Ghusl.\n2. First removing any visible impurity and performing Istinja.\n3. Then performing Wudhu.\n4. Rubbing the body.\n5. Pouring water over the entire body three times.",
  },
  {
    number: 4,
    nameAr: "مَکْرُوْہَاتِ غُسْل",
    nameEn: "Disliked Acts During Ghusl (Makroohat)",
    arabic: "",
    content: "غسل کی مکروہات یہ ہیں:\n\n۱۔ پانی بہت زیادہ گرانا۔\n۲۔ اتنا کم پانی لینا کہ اچھی طرح غسل نہ کر سکے۔\n۳۔ ننگا ہونے کی حالت میں غسل کرتے وقت کسی سے کلام کرنا یا قبلہ رو ہوکر غسل کرنا۔\n\nمسئلہ: کسی کو اپنی شرم کی جگہ یا رانیں یا گھٹنے دکھانا حرام ہے۔",
    translation: "Disliked (Makrooh) acts during Ghusl:\n\n1. Wasting too much water.\n2. Using so little water that you cannot perform Ghusl properly.\n3. Talking to someone or facing the Qibla while bathing naked.\n\nRuling: It is Haram to show one's private parts, thighs, or knees to others.",
  },
];

export const essentialDuas = [
  {
    nameAr: "دُعَاءِ قَبْلَ الطَّعَام",
    nameEn: "Dua Before Eating",
    arabic: "بِسْمِ اللّٰهِ وَعَلٰى بَرَكَةِ اللّٰهِ",
    translation: "In the name of Allah and with the blessings of Allah.",
  },
  {
    nameAr: "دُعَاءِ بَعْدَ الطَّعَام",
    nameEn: "Dua After Eating",
    arabic: "اَلْحَمْدُ لِلّٰهِ الَّذِيْ اَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِيْنَ",
    translation: "All praise is for Allah who gave us food and drink and made us Muslims.",
  },
  {
    nameAr: "دُعَاءِ سَوْنَے سَے پَہْلَے",
    nameEn: "Dua Before Sleeping",
    arabic: "اَللّٰهُمَّ بِاسْمِكَ اَمُوْتُ وَاَحْيَا",
    translation: "O Allah, in Your name I die and I live.",
  },
  {
    nameAr: "دُعَاءِ جَاگْنَے کَے بَعْد",
    nameEn: "Dua After Waking Up",
    arabic: "اَلْحَمْدُ لِلّٰهِ الَّذِيْ اَحْيَانَا بَعْدَ مَآ اَمَاتَنَا وَاِلَيْهِ النُّشُوْرُ",
    translation: "All praise is for Allah who gave us life after death, and to Him is the return.",
  },
  {
    nameAr: "دُعَاءِ دَاخِلِ مَسْجِد",
    nameEn: "Dua Entering Masjid",
    arabic: "اَللّٰهُمَّ افْتَحْ لِيْ اَبْوَابَ رَحْمَتِكَ",
    translation: "O Allah, open the doors of Your mercy for me.",
  },
  {
    nameAr: "دُعَاءِ خُرُوْجِ مَسْجِد",
    nameEn: "Dua Leaving Masjid",
    arabic: "اَللّٰهُمَّ اِنِّيْ اَسْئَلُكَ مِنْ فَضْلِكَ",
    translation: "O Allah, I ask You from Your bounty.",
  },
  {
    nameAr: "دُعَاءِ سَفَر",
    nameEn: "Dua for Travel",
    arabic: "سُبْحَانَ الَّذِيْ سَخَّرَ لَنَا هٰذَا وَمَا كُنَّا لَهٗ مُقْرِنِيْنَ وَاِنَّآ اِلٰى رَبِّنَا لَمُنْقَلِبُوْنَ",
    translation: "Glory be to Him who has subjected this to us, and we were not capable of doing that, and surely to our Lord we will return.",
  },
];

export const tayammumKaBiyan = [
  {
    number: 1,
    nameAr: "تَیَمُّم کَا طَرِیقَہ",
    nameEn: "Method of Tayammum",
    arabic: "",
    content: "جب پانی نہ ملے یا پانی استعمال کرنے سے بیماری بڑھنے کا خطرہ ہو تو پاک مٹی سے تیمم کریں۔\n\nطریقہ:\n۱۔ پاک مٹی یا پتھر پر دونوں ہاتھ مار کر چہرے پر پھیریں۔\n۲۔ دوبارہ ہاتھ مار کر پہلے بایاں ہاتھ دائیں ہاتھ پر اور پھر دایاں ہاتھ بائیں ہاتھ پر کہنیوں تک پھیریں۔",
    translation: "When water is not available, or using water may worsen an illness, perform Tayammum with clean earth.\n\nMethod:\n1. Strike both hands on clean earth/stone and wipe over the face.\n2. Strike again and wipe left hand over right arm, then right hand over left arm up to the elbows.",
  },
  {
    number: 2,
    nameAr: "تَیَمُّم کے فَرَائِض",
    nameEn: "Obligatory Acts of Tayammum (3 Faraidh)",
    arabic: "",
    content: "تیمم کے تین فرض ہیں:\n\n۱۔ نیت کرنا۔\n۲۔ پورا چہرہ مسح کرنا۔\n۳۔ دونوں ہاتھ کہنیوں سمیت مسح کرنا۔",
    translation: "Tayammum has 3 obligatory acts:\n\n1. Making intention (Niyyah).\n2. Wiping the entire face.\n3. Wiping both hands including elbows.",
  },
  {
    number: 3,
    nameAr: "نَوَاقِضِ تَیَمُّم",
    nameEn: "Things That Break Tayammum",
    arabic: "",
    content: "وہ تمام چیزیں جو وضو توڑ دیتی ہیں وہ تیمم بھی توڑ دیتی ہیں۔\nاس کے علاوہ پانی مل جانے سے بھی تیمم ٹوٹ جاتا ہے۔\n\nمسئلہ: اگر تیمم کرکے نماز پڑھ لی اور بعد میں پانی مل جائے تو نماز دوبارہ نہیں پڑھنی۔",
    translation: "All things that break Wudu also break Tayammum.\nAdditionally, finding water also breaks Tayammum.\n\nRuling: If you prayed with Tayammum and later found water, you don't need to repeat the prayer.",
  },
];

export const namazKaBiyan = [
  {
    number: 1,
    nameAr: "نَمَاز کی اَہَمِیَّت",
    nameEn: "Importance of Namaz (Salah)",
    arabic: "",
    content: "نماز اسلام کا سب سے اہم رکن ہے۔ ایمان کے بعد سب سے پہلا فرض نماز ہے۔ نماز فرض ہونے کے دلائل قرآن و حدیث سے ثابت ہیں۔\n\nحدیث: نبی کریم ﷺ نے فرمایا: قیامت کے دن سب سے پہلے نماز کا حساب ہوگا۔ اگر نماز درست ہوئی تو باقی اعمال بھی درست ہوں گے اور اگر نماز درست نہ ہوئی تو باقی اعمال بھی درست نہ ہوں گے۔",
    translation: "Namaz is the most important pillar of Islam. After Iman (faith), Namaz is the first obligation. Its obligation is proven from Quran and Hadith.\n\nHadith: The Prophet (PBUH) said: On the Day of Judgment, Namaz will be accounted for first. If Namaz is correct, other deeds will be correct too; if Namaz is not correct, other deeds will also not be correct.",
  },
  {
    number: 2,
    nameAr: "پَانچ نَمَازوں کی رَکعَات",
    nameEn: "Rakaat of Five Daily Prayers",
    arabic: "",
    content: "فجر: ۲ سنت مؤکدہ + ۲ فرض = ۴ رکعت\n\nظہر: ۴ سنت مؤکدہ + ۴ فرض + ۲ سنت مؤکدہ + ۲ نفل = ۱۲ رکعت\n\nعصر: ۴ سنت غیر مؤکدہ + ۴ فرض = ۸ رکعت\n\nمغرب: ۳ فرض + ۲ سنت مؤکدہ + ۲ نفل = ۷ رکعت\n\nعشاء: ۴ سنت غیر مؤکدہ + ۴ فرض + ۲ سنت مؤکدہ + ۳ وتر واجب + ۲ نفل = ۱۵ رکعت\n\nکل: ۴۶ رکعت",
    translation: "Fajr: 2 Sunnah Muakkadah + 2 Fard = 4 Rakaat\n\nZuhr: 4 Sunnah Muakkadah + 4 Fard + 2 Sunnah Muakkadah + 2 Nafl = 12 Rakaat\n\nAsr: 4 Sunnah Ghair Muakkadah + 4 Fard = 8 Rakaat\n\nMaghrib: 3 Fard + 2 Sunnah Muakkadah + 2 Nafl = 7 Rakaat\n\nIsha: 4 Sunnah Ghair Muakkadah + 4 Fard + 2 Sunnah Muakkadah + 3 Witr Wajib + 2 Nafl = 15 Rakaat\n\nTotal: 46 Rakaat",
  },
  {
    number: 3,
    nameAr: "جُمُعَہ کی نَمَاز",
    nameEn: "Juma (Friday) Prayer",
    arabic: "",
    content: "جمعہ کی نماز ظہر کے وقت ہوتی ہے۔ جمعہ کی نماز ہر عاقل بالغ آزاد مقیم مرد پر فرض ہے۔\n\nجمعہ کی رکعتیں:\n۴ سنت مؤکدہ + ۲ فرض (خطبے کے بعد) + ۴ سنت مؤکدہ + ۲ سنت مؤکدہ + ۲ نفل = ۱۴ رکعت",
    translation: "Juma prayer is performed at the time of Zuhr. It is obligatory on every sane, adult, free, resident male.\n\nJuma Rakaat:\n4 Sunnah Muakkadah + 2 Fard (after Khutbah) + 4 Sunnah Muakkadah + 2 Sunnah Muakkadah + 2 Nafl = 14 Rakaat",
  },
  {
    number: 4,
    nameAr: "نَمَاز کی نِیَّت",
    nameEn: "Niyyat (Intention) for Each Prayer",
    arabic: "",
    content: "نیت فجر: نیت کرتا ہوں دو رکعت نماز فرض فجر کی، واسطے اللہ تعالیٰ کے، رخ میرا کعبہ شریف کی طرف، اللہ اکبر۔\n\nنیت ظہر: نیت کرتا ہوں چار رکعت نماز فرض وقت ظہر کی، واسطے اللہ تعالیٰ کے، رخ میرا کعبہ شریف کی طرف، اللہ اکبر۔\n\nنیت عصر: نیت کرتا ہوں چار رکعت نماز فرض وقت عصر کی، واسطے اللہ تعالیٰ کے، رخ میرا کعبہ شریف کی طرف، اللہ اکبر۔\n\nنیت مغرب: نیت کرتا ہوں تین رکعت نماز فرض وقت مغرب کی، واسطے اللہ تعالیٰ کے، رخ میرا کعبہ شریف کی طرف، اللہ اکبر۔\n\nنیت عشاء: نیت کرتا ہوں چار رکعت نماز فرض وقت عشاء کی، واسطے اللہ تعالیٰ کے، رخ میرا کعبہ شریف کی طرف، اللہ اکبر۔",
    translation: "Fajr Niyyat: I intend to pray 2 Rakaat Fard of Fajr, for the sake of Allah, facing the Ka'bah. Allahu Akbar.\n\nZuhr Niyyat: I intend to pray 4 Rakaat Fard of Zuhr, for the sake of Allah, facing the Ka'bah. Allahu Akbar.\n\nAsr Niyyat: I intend to pray 4 Rakaat Fard of Asr, for the sake of Allah, facing the Ka'bah. Allahu Akbar.\n\nMaghrib Niyyat: I intend to pray 3 Rakaat Fard of Maghrib, for the sake of Allah, facing the Ka'bah. Allahu Akbar.\n\nIsha Niyyat: I intend to pray 4 Rakaat Fard of Isha, for the sake of Allah, facing the Ka'bah. Allahu Akbar.",
  },
];

export const azanKaBiyan = [
  {
    number: 1,
    nameAr: "اَذَان کے کَلِمَات",
    nameEn: "Words of Azan (Call to Prayer)",
    arabic: "اَللّٰهُ اَكْبَرُ اَللّٰهُ اَكْبَرُ\nاَللّٰهُ اَكْبَرُ اَللّٰهُ اَكْبَرُ\nاَشْهَدُ اَنْ لَّآ اِلٰهَ اِلَّا اللّٰهُ\nاَشْهَدُ اَنْ لَّآ اِلٰهَ اِلَّا اللّٰهُ\nاَشْهَدُ اَنَّ مُحَمَّدًا رَّسُوْلُ اللّٰهِ\nاَشْهَدُ اَنَّ مُحَمَّدًا رَّسُوْلُ اللّٰهِ\nحَیَّ عَلَى الصَّلٰوةِ حَیَّ عَلَى الصَّلٰوةِ\nحَیَّ عَلَى الْفَلَاحِ حَیَّ عَلَى الْفَلَاحِ\nاَللّٰهُ اَكْبَرُ اَللّٰهُ اَكْبَرُ\nلَآ اِلٰهَ اِلَّا اللّٰهُ",
    content: "اذان کے جواب میں سننے والا بھی وہی الفاظ دہرائے۔ البتہ حَیَّ عَلَى الصَّلٰوة اور حَیَّ عَلَى الْفَلَاح کے جواب میں لَا حَوْلَ وَلَا قُوَّةَ اِلَّا بِاللّٰهِ کہے۔\n\nفجر کی اذان میں حَیَّ عَلَى الْفَلَاح کے بعد اَلصَّلٰوةُ خَیْرٌ مِّنَ النَّوْمِ (دو بار) کہا جاتا ہے۔",
    translation: "In response to Azan, the listener repeats the same words. However, in response to 'Hayya alas-Salah' and 'Hayya alal-Falah', say 'La hawla wa la quwwata illa billah'.\n\nIn Fajr Azan, after 'Hayya alal-Falah', 'As-Salatu khayrum minan-nawm' (prayer is better than sleep) is said twice.",
  },
  {
    number: 2,
    nameAr: "اِقَامَت",
    nameEn: "Iqamah (Second Call Before Prayer)",
    arabic: "",
    content: "اقامت کے الفاظ اذان کی طرح ہیں البتہ حَیَّ عَلَى الْفَلَاح کے بعد قَدْ قَامَتِ الصَّلٰوة قَدْ قَامَتِ الصَّلٰوة کہا جاتا ہے۔\n\nاذان اور اقامت کے بعد دعا:\nاَللّٰهُمَّ رَبَّ هٰذِهِ الدَّعْوَةِ التَّامَّةِ وَالصَّلٰوةِ الْقَائِمَةِ اٰتِ مُحَمَّدَنِ الْوَسِيْلَةَ وَالْفَضِيْلَةَ وَابْعَثْهُ مَقَامًا مَّحْمُوْدَنِ الَّذِيْ وَعَدْتَّهٗ",
    translation: "Iqamah words are like Azan but after 'Hayya alal-Falah', say 'Qad qaamatis-salah' twice.\n\nDua after Azan and Iqamah:\nO Allah, Lord of this perfect call and the prayer about to be established, grant Muhammad the Wasilah and superiority, and raise him to the praised station You have promised him.",
  },
];

export const azkarNamaz = [
  {
    number: 1,
    nameAr: "ثَنَاء",
    nameEn: "Sana (Opening Praise)",
    arabic: "سُبْحَانَكَ اللّٰهُمَّ وَبِحَمْدِكَ وَتَبَارَكَ اسْمُكَ وَتَعَالٰى جَدُّكَ وَلَا اِلٰهَ غَيْرُكَ",
    content: "نماز میں تکبیر تحریمہ کے بعد سب سے پہلے ثناء پڑھی جاتی ہے۔",
    translation: "Glory be to You O Allah, and praise be to You, blessed is Your name, exalted is Your majesty, and there is no god but You.\n\nThis is recited after Takbeer Tahreema at the beginning of prayer.",
  },
  {
    number: 2,
    nameAr: "تَعَوُّذ",
    nameEn: "Ta'awwuz (Seeking Refuge)",
    arabic: "اَعُوْذُ بِاللّٰهِ مِنَ الشَّيْطٰنِ الرَّجِيْمِ",
    content: "ثناء کے بعد تعوذ پڑھی جاتی ہے۔",
    translation: "I seek refuge with Allah from Shaytan the accursed.\n\nRecited after Sana.",
  },
  {
    number: 3,
    nameAr: "تَسْمِیَہ",
    nameEn: "Tasmiya (Bismillah)",
    arabic: "بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيْمِ",
    content: "تعوذ کے بعد تسمیہ پڑھی جاتی ہے۔",
    translation: "In the name of Allah, the Most Gracious, the Most Merciful.\n\nRecited after Ta'awwuz.",
  },
  {
    number: 4,
    nameAr: "سُوْرَةُ الْفَاتِحَہ",
    nameEn: "Surah Al-Fatiha",
    arabic: "اَلْحَمْدُ لِلّٰهِ رَبِّ الْعَالَمِيْنَ\nاَلرَّحْمٰنِ الرَّحِيْمِ\nمَالِكِ يَوْمِ الدِّيْنِ\nاِيَّاكَ نَعْبُدُ وَاِيَّاكَ نَسْتَعِيْنُ\nاِهْدِنَا الصِّرَاطَ الْمُسْتَقِيْمَ\nصِرَاطَ الَّذِيْنَ اَنْعَمْتَ عَلَيْهِمْ\nغَيْرِ الْمَغْضُوْبِ عَلَيْهِمْ وَلَا الضَّالِّيْنَ\nاٰمِيْن",
    content: "سورۃ الفاتحہ ہر رکعت میں پڑھنا فرض ہے۔",
    translation: "All praise is for Allah, Lord of all the worlds.\nThe Most Gracious, the Most Merciful.\nMaster of the Day of Judgment.\nYou alone we worship, and You alone we ask for help.\nGuide us on the Straight Path.\nThe path of those You have blessed.\nNot of those who earned Your anger, nor of those who went astray.\nAmeen.\n\nReciting Surah Al-Fatiha is obligatory in every Rakaat.",
  },
  {
    number: 5,
    nameAr: "سُوْرَةُ الْاِخْلَاص",
    nameEn: "Surah Al-Ikhlas",
    arabic: "قُلْ هُوَ اللّٰهُ اَحَدٌ\nاَللّٰهُ الصَّمَدُ\nلَمْ يَلِدْ وَلَمْ يُوْلَدْ\nوَلَمْ يَكُنْ لَّهٗ كُفُوًا اَحَدٌ",
    content: "فاتحہ کے بعد کوئی سورت ملائی جاتی ہے۔ یہ سورۃ الاخلاص ہے۔",
    translation: "Say: He is Allah, the One.\nAllah, the Eternal Refuge.\nHe neither begets nor is born.\nNor is there any equivalent to Him.\n\nA Surah is added after Fatiha. This is Surah Al-Ikhlas.",
  },
  {
    number: 6,
    nameAr: "سُوْرَةُ الْکَوْثَر",
    nameEn: "Surah Al-Kausar",
    arabic: "اِنَّآ اَعْطَيْنَاكَ الْكَوْثَرَ\nفَصَلِّ لِرَبِّكَ وَانْحَرْ\nاِنَّ شَانِئَكَ هُوَ الْاَبْتَرُ",
    content: "",
    translation: "Indeed, We have granted you Al-Kausar.\nSo pray to your Lord and sacrifice.\nIndeed, your enemy is the one cut off.",
  },
  {
    number: 7,
    nameAr: "سُوْرَةُ الْفَلَق",
    nameEn: "Surah Al-Falaq",
    arabic: "قُلْ اَعُوْذُ بِرَبِّ الْفَلَقِ\nمِنْ شَرِّ مَا خَلَقَ\nوَمِنْ شَرِّ غَاسِقٍ اِذَا وَقَبَ\nوَمِنْ شَرِّ النَّفّٰثٰتِ فِي الْعُقَدِ\nوَمِنْ شَرِّ حَاسِدٍ اِذَا حَسَدَ",
    content: "",
    translation: "Say: I seek refuge with the Lord of the daybreak.\nFrom the evil of what He has created.\nAnd from the evil of darkness when it settles.\nAnd from the evil of those who blow on knots.\nAnd from the evil of an envier when he envies.",
  },
  {
    number: 8,
    nameAr: "سُوْرَةُ النَّاس",
    nameEn: "Surah An-Naas",
    arabic: "قُلْ اَعُوْذُ بِرَبِّ النَّاسِ\nمَلِكِ النَّاسِ\nاِلٰهِ النَّاسِ\nمِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ\nاَلَّذِيْ يُوَسْوِسُ فِيْ صُدُوْرِ النَّاسِ\nمِنَ الْجِنَّةِ وَالنَّاسِ",
    content: "",
    translation: "Say: I seek refuge with the Lord of mankind.\nThe King of mankind.\nThe God of mankind.\nFrom the evil of the whisperer who withdraws.\nWho whispers in the hearts of mankind.\nFrom among the Jinn and mankind.",
  },
  {
    number: 9,
    nameAr: "رُکُوع کی تَسْبِیح",
    nameEn: "Tasbeeh of Ruku (Bowing)",
    arabic: "سُبْحَانَ رَبِّيَ الْعَظِيْمِ",
    content: "رکوع میں کم از کم تین مرتبہ پڑھیں۔",
    translation: "Glory be to my Lord, the Almighty.\n\nRecite at least 3 times in Ruku.",
  },
  {
    number: 10,
    nameAr: "قَوْمَہ (رُکُوع سے اُٹھنا)",
    nameEn: "Qawma (Rising from Ruku)",
    arabic: "سَمِعَ اللّٰهُ لِمَنْ حَمِدَهٗ\nرَبَّنَا لَكَ الْحَمْدُ",
    content: "رکوع سے اٹھتے ہوئے سَمِعَ اللّٰهُ لِمَنْ حَمِدَهٗ کہیں اور کھڑے ہوکر رَبَّنَا لَكَ الْحَمْدُ کہیں۔",
    translation: "Allah hears the one who praises Him.\nOur Lord, to You belongs all praise.\n\nSay 'Sami Allahu liman hamidah' while rising, then 'Rabbana lakal hamd' when standing.",
  },
  {
    number: 11,
    nameAr: "سَجْدَے کی تَسْبِیح",
    nameEn: "Tasbeeh of Sajda (Prostration)",
    arabic: "سُبْحَانَ رَبِّيَ الْاَعْلٰى",
    content: "سجدے میں کم از کم تین مرتبہ پڑھیں۔",
    translation: "Glory be to my Lord, the Most High.\n\nRecite at least 3 times in Sajda.",
  },
  {
    number: 12,
    nameAr: "تَشَہُّد (اَلتَّحِیَّات)",
    nameEn: "Tashahhud (At-Tahiyyat)",
    arabic: "اَلتَّحِيَّاتُ لِلّٰهِ وَالصَّلَوَاتُ وَالطَّيِّبَاتُ\nاَلسَّلَامُ عَلَيْكَ اَيُّهَا النَّبِيُّ وَرَحْمَةُ اللّٰهِ وَبَرَكَاتُهٗ\nاَلسَّلَامُ عَلَيْنَا وَعَلٰى عِبَادِ اللّٰهِ الصَّالِحِيْنَ\nاَشْهَدُ اَنْ لَّآ اِلٰهَ اِلَّا اللّٰهُ\nوَاَشْهَدُ اَنَّ مُحَمَّدًا عَبْدُهٗ وَرَسُوْلُهٗ",
    content: "دو رکعت کے بعد بیٹھ کر التحیات پڑھیں۔",
    translation: "All verbal, physical, and monetary worship is for Allah.\nPeace be upon you, O Prophet, and the mercy of Allah and His blessings.\nPeace be upon us and upon the righteous servants of Allah.\nI bear witness that there is no god but Allah.\nAnd I bear witness that Muhammad is His servant and His Messenger.\n\nRecite At-Tahiyyat while sitting after 2 Rakaat.",
  },
  {
    number: 13,
    nameAr: "دُرُوْدِ اِبْرَاہِیم",
    nameEn: "Durood Ibrahim",
    arabic: "اَللّٰهُمَّ صَلِّ عَلٰى مُحَمَّدٍ وَّعَلٰى اٰلِ مُحَمَّدٍ\nكَمَا صَلَّيْتَ عَلٰى اِبْرَاهِيْمَ وَعَلٰى اٰلِ اِبْرَاهِيْمَ\nاِنَّكَ حَمِيْدٌ مَّجِيْدٌ\nاَللّٰهُمَّ بَارِكْ عَلٰى مُحَمَّدٍ وَّعَلٰى اٰلِ مُحَمَّدٍ\nكَمَا بَارَكْتَ عَلٰى اِبْرَاهِيْمَ وَعَلٰى اٰلِ اِبْرَاهِيْمَ\nاِنَّكَ حَمِيْدٌ مَّجِيْدٌ",
    content: "آخری قعدے میں تشہد کے بعد درود ابراہیم پڑھیں۔",
    translation: "O Allah, send blessings upon Muhammad and upon the family of Muhammad,\nas You sent blessings upon Ibrahim and upon the family of Ibrahim.\nIndeed, You are Praiseworthy and Glorious.\nO Allah, bless Muhammad and the family of Muhammad,\nas You blessed Ibrahim and the family of Ibrahim.\nIndeed, You are Praiseworthy and Glorious.\n\nRecite Durood Ibrahim after Tashahhud in the last sitting.",
  },
  {
    number: 14,
    nameAr: "دُعَاءِ بَعدَ دُرُوْد",
    nameEn: "Dua After Durood (Before Salam)",
    arabic: "اَللّٰهُمَّ اِنِّيْ ظَلَمْتُ نَفْسِيْ ظُلْمًا كَثِيْرًا وَلَا يَغْفِرُ الذُّنُوْبَ اِلَّا اَنْتَ فَاغْفِرْ لِيْ مَغْفِرَةً مِّنْ عِنْدِكَ وَارْحَمْنِيْ اِنَّكَ اَنْتَ الْغَفُوْرُ الرَّحِيْمُ",
    content: "درود کے بعد سلام سے پہلے یہ دعا پڑھیں۔",
    translation: "O Allah, I have wronged myself greatly, and no one forgives sins but You. So grant me forgiveness from You and have mercy on me. Indeed, You are the Forgiving, the Merciful.\n\nRecite this dua after Durood, before Salam.",
  },
  {
    number: 15,
    nameAr: "سَلَام",
    nameEn: "Salam (Ending Prayer)",
    arabic: "اَلسَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللّٰهِ",
    content: "پہلے دائیں طرف اور پھر بائیں طرف سلام پھیریں۔ اس سے نماز مکمل ہوتی ہے۔",
    translation: "Peace be upon you and the mercy of Allah.\n\nTurn right first, then left to give Salam. This completes the prayer.",
  },
];

export const namazKaTariqa = [
  {
    number: 1,
    nameAr: "نَمَاز کَا طَرِیقَہ",
    nameEn: "Step-by-Step Method of Namaz",
    arabic: "",
    content: "۱۔ قبلہ رخ کھڑے ہوں اور نیت کریں۔\n۲۔ دونوں ہاتھ کانوں تک اٹھا کر اللہ اکبر کہیں (تکبیر تحریمہ)۔\n۳۔ ناف کے نیچے ہاتھ باندھیں (مرد)، سینے پر (عورتیں)۔\n۴۔ ثناء پڑھیں: سبحانک اللھم وبحمدک...\n۵۔ تعوذ پڑھیں: اعوذ باللہ من الشیطان الرجیم\n۶۔ تسمیہ پڑھیں: بسم اللہ الرحمن الرحیم\n۷۔ سورۃ الفاتحہ پڑھیں۔ آخر میں آمین کہیں۔\n۸۔ کوئی سورت ملائیں۔\n۹۔ اللہ اکبر کہتے ہوئے رکوع میں جائیں۔ سُبْحَانَ رَبِّيَ الْعَظِيْمِ تین بار پڑھیں۔\n۱۰۔ سَمِعَ اللّٰهُ لِمَنْ حَمِدَهٗ کہتے ہوئے کھڑے ہوں۔ رَبَّنَا لَكَ الْحَمْدُ کہیں۔\n۱۱۔ اللہ اکبر کہتے ہوئے سجدے میں جائیں۔ سُبْحَانَ رَبِّيَ الْاَعْلٰى تین بار پڑھیں۔\n۱۲۔ اللہ اکبر کہتے ہوئے بیٹھیں (جلسہ)۔\n۱۳۔ دوبارہ اللہ اکبر کہتے ہوئے سجدہ کریں۔\n۱۴۔ اللہ اکبر کہتے ہوئے دوسری رکعت کے لیے کھڑے ہوں۔\n(دوسری رکعت میں ثناء، تعوذ، تسمیہ نہیں، صرف بسم اللہ کے بعد فاتحہ اور سورت)\n۱۵۔ دوسری رکعت کے سجدوں کے بعد بیٹھ کر التحیات پڑھیں۔\n(اگر دو رکعت کی نماز ہے تو درود ابراہیم، دعا اور سلام)\n۱۶۔ تین یا چار رکعت ہوں تو التحیات کے بعد کھڑے ہوں۔\n۱۷۔ آخری قعدے میں التحیات، درود ابراہیم، دعا پڑھ کر سلام پھیریں۔",
    translation: "1. Stand facing Qibla and make intention.\n2. Raise hands to ears and say Allahu Akbar (Takbeer Tahreema).\n3. Fold hands below navel (men), on chest (women).\n4. Recite Sana: Subhanaka Allahumma...\n5. Recite Ta'awwuz: A'udhu billahi minash-shaytanir-rajeem\n6. Recite Tasmiya: Bismillahir-Rahmanir-Raheem\n7. Recite Surah Al-Fatiha. Say Ameen at the end.\n8. Add another Surah.\n9. Say Allahu Akbar and go into Ruku. Recite Subhana Rabbiyal-Azeem 3 times.\n10. Rise saying Sami'Allahu liman hamidah. Say Rabbana lakal-hamd.\n11. Say Allahu Akbar and go into Sajda. Recite Subhana Rabbiyal-A'la 3 times.\n12. Say Allahu Akbar and sit (Jalsa).\n13. Say Allahu Akbar and do second Sajda.\n14. Rise for second Rakaat saying Allahu Akbar.\n(In 2nd Rakaat: no Sana/Ta'awwuz/Tasmiya, start with Bismillah then Fatiha and Surah)\n15. After second Rakaat prostrations, sit and recite At-Tahiyyat.\n(If 2 Rakaat prayer: add Durood Ibrahim, Dua, then Salam)\n16. For 3 or 4 Rakaat prayers, stand after At-Tahiyyat.\n17. In the final sitting, recite At-Tahiyyat, Durood Ibrahim, Dua, then give Salam.",
  },
  {
    number: 2,
    nameAr: "مَرْد اور عَوْرَت کی نَمَاز میں فَرْق",
    nameEn: "Differences Between Men's and Women's Prayer",
    arabic: "",
    content: "۱۔ مرد تکبیر تحریمہ میں ہاتھ کانوں تک اٹھائے، عورت کندھوں تک۔\n۲۔ مرد ناف کے نیچے ہاتھ باندھے، عورت سینے پر۔\n۳۔ مرد رکوع میں کمر سیدھی کرے ہاتھ گھٹنوں پر، عورت تھوڑا سا جھکے۔\n۴۔ مرد سجدے میں بازو پہلو سے الگ رکھے، عورت بازو جسم سے ملا کر رکھے۔\n۵۔ مرد سجدے میں پیٹ رانوں سے الگ رکھے، عورت پیٹ رانوں سے ملا کر رکھے۔\n۶۔ مرد بیٹھنے میں بایاں پاؤں بچھا کر بیٹھے، عورت دونوں پاؤں دائیں طرف نکال کر بیٹھے۔\n۷۔ عورت نماز آہستہ آواز سے پڑھے۔",
    translation: "1. Men raise hands to ears in Takbeer, women to shoulders.\n2. Men fold hands below navel, women on chest.\n3. Men straighten back in Ruku with hands on knees, women bend slightly.\n4. Men keep arms away from sides in Sajda, women keep arms close to body.\n5. Men keep stomach away from thighs in Sajda, women keep stomach against thighs.\n6. Men sit on left foot, women sit with both feet to the right.\n7. Women pray silently.",
  },
];

export const namazWitr = [
  {
    number: 1,
    nameAr: "نَمَاز وِتر اور دُعَائے قُنُوت",
    nameEn: "Witr Prayer & Dua-e-Qunoot",
    arabic: "اَللّٰهُمَّ اِنَّا نَسْتَعِيْنُكَ وَنَسْتَغْفِرُكَ وَنُؤْمِنُ بِكَ وَنَتَوَكَّلُ عَلَيْكَ وَنُثْنِيْ عَلَيْكَ الْخَيْرَ وَنَشْكُرُكَ وَلَا نَكْفُرُكَ وَنَخْلَعُ وَنَتْرُكُ مَنْ يَّفْجُرُكَ\nاَللّٰهُمَّ اِيَّاكَ نَعْبُدُ وَلَكَ نُصَلِّيْ وَنَسْجُدُ وَاِلَيْكَ نَسْعٰى وَنَحْفِدُ وَنَرْجُوْ رَحْمَتَكَ وَنَخْشٰى عَذَابَكَ اِنَّ عَذَابَكَ بِالْكُفَّارِ مُلْحِقٌ",
    content: "وتر کی نماز عشاء کے بعد تین رکعت واجب ہے۔\n\nطریقہ: تیسری رکعت میں سورۃ فاتحہ اور سورت پڑھ کر اللہ اکبر کہتے ہوئے کانوں تک ہاتھ اٹھائیں اور پھر باندھ لیں اور دعائے قنوت پڑھیں۔ پھر رکوع سجدے کریں۔",
    translation: "O Allah, we seek Your help and seek Your forgiveness, and we believe in You and rely upon You, and we praise You with all goodness, and we thank You and are not ungrateful to You, and we separate from and leave those who disobey You.\nO Allah, You alone we worship, and to You we pray and prostrate, and toward You we hasten, and we hope for Your mercy and fear Your punishment. Surely, Your punishment will overtake the disbelievers.\n\nWitr prayer is 3 Rakaat Wajib after Isha.\n\nMethod: In the 3rd Rakaat, after Fatiha and Surah, say Allahu Akbar while raising hands to ears, then fold them and recite Dua-e-Qunoot. Then do Ruku and Sajda.",
  },
];

export const faraizNamaz = [
  {
    number: 1,
    nameAr: "نَمَاز کے فَرَائِض",
    nameEn: "Obligatory Acts of Namaz (12 Faraidh)",
    arabic: "",
    content: "نماز کے بارہ (۱۲) فرائض:\n\nسات شرائط (نماز سے پہلے):\n۱۔ بدن پاک ہونا\n۲۔ کپڑے پاک ہونا\n۳۔ نماز کی جگہ پاک ہونا\n۴۔ ستر ڈھکنا (مرد: ناف سے گھٹنوں تک، عورت: چہرے، ہاتھوں اور پاؤں کے سوا پورا جسم)\n۵۔ قبلہ رخ ہونا\n۶۔ وقت کا ہونا\n۷۔ نیت کرنا\n\nپانچ ارکان (نماز کے اندر):\n۸۔ تکبیر تحریمہ (اللہ اکبر کہنا)\n۹۔ قیام (کھڑا ہونا)\n۱۰۔ قراءت (قرآن پڑھنا)\n۱۱۔ رکوع کرنا\n۱۲۔ سجدہ کرنا",
    translation: "12 Obligatory Acts of Namaz:\n\n7 Pre-conditions (before prayer):\n1. Body must be clean\n2. Clothes must be clean\n3. Place of prayer must be clean\n4. Covering Awrah (Men: navel to knees, Women: entire body except face, hands, and feet)\n5. Facing Qibla\n6. Correct prayer time\n7. Making intention (Niyyah)\n\n5 Pillars (during prayer):\n8. Takbeer Tahreema (saying Allahu Akbar)\n9. Qiyam (standing)\n10. Qira'at (reciting Quran)\n11. Performing Ruku (bowing)\n12. Performing Sajda (prostration)",
  },
  {
    number: 2,
    nameAr: "وَاجِبَاتِ نَمَاز",
    nameEn: "Wajibat (Necessary Acts) of Namaz",
    arabic: "",
    content: "نماز کے واجبات:\n\n۱۔ سورۃ الفاتحہ پڑھنا\n۲۔ فاتحہ کے ساتھ کوئی سورت ملانا\n۳۔ فرض کی پہلی دو رکعتوں میں قراءت اور نفل و وتر کی ہر رکعت میں قراءت\n۴۔ رکوع و سجود میں تسبیحات\n۵۔ قعدۂ اولیٰ میں التحیات\n۶۔ نماز سلام سے ختم کرنا",
    translation: "Necessary Acts (Wajibat) of Namaz:\n\n1. Reciting Surah Al-Fatiha\n2. Adding a Surah after Fatiha\n3. Recitation in first 2 Rakaat of Fard, and every Rakaat of Nafl and Witr\n4. Tasbeeh in Ruku and Sujood\n5. At-Tahiyyat in first Qa'dah\n6. Ending prayer with Salam",
  },
  {
    number: 3,
    nameAr: "مُفْسِدَاتِ نَمَاز",
    nameEn: "Things That Break Namaz (Mufsidaat)",
    arabic: "",
    content: "یہ چیزیں نماز توڑ دیتی ہیں:\n\n۱۔ نماز میں بات کرنا\n۲۔ کسی کو سلام کرنا\n۳۔ سلام کا جواب دینا\n۴۔ اُف، آہ کہنا\n۵۔ کھانسنے میں آواز نکالنا (بلا عذر)\n۶۔ قرآن دیکھ کر پڑھنا\n۷۔ سینہ قبلے سے پھیرنا\n۸۔ عمل کثیر یعنی زیادہ کام کرنا مثلاً ایک ساتھ دونوں ہاتھوں سے کوئی کام کرنا\n۹۔ قصداً بھول کر کچھ کھانا پینا\n۱۰۔ قبلے سے سینے کا پھر جانا\n۱۱۔ درد یا مصیبت کی وجہ سے اس طرح رونا کہ آواز میں حروف نکل جائیں\n۱۲۔ نماز میں ایسی آواز سے ہنسنا جسے کم از کم خود سن لے\n۱۳۔ امام سے آگے بڑھ جانا",
    translation: "Things that break Namaz:\n\n1. Talking during prayer\n2. Greeting someone\n3. Replying to a greeting\n4. Saying 'Uff' or 'Aah'\n5. Making sounds while coughing (without excuse)\n6. Reading Quran by looking at it\n7. Turning chest away from Qibla\n8. Excessive movement (e.g., using both hands for something)\n9. Deliberately eating or drinking\n10. Chest turning away from Qibla\n11. Crying due to pain in a way that letters come out in the voice\n12. Laughing audibly (at least hearing it yourself)\n13. Going ahead of the Imam",
  },
  {
    number: 4,
    nameAr: "نَمَاز کی سُنَّتیں",
    nameEn: "Sunnats of Namaz",
    arabic: "",
    content: "یہ چیزیں نماز میں سنت ہیں:\n\n۱۔ تکبیر تحریمہ کے وقت مردوں کو دونوں ہاتھ کانوں تک اٹھانا اور عورتوں کو سینے تک اٹھانا۔\n۲۔ مردوں کو ناف کے نیچے اور عورتوں کو سینے پر ہاتھ باندھنا۔\n۳۔ ثنا یعنی سُبْحَانَكَ اللّٰهُمَّ آخر تک پڑھنا۔\n۴۔ اَعُوْذُ بِاللّٰهِ (پوری) پڑھنا۔\n۵۔ بِسْمِ اللّٰهِ (پوری) پڑھنا۔\n۶۔ ایک رکن سے دوسرے رکن کو منتقل ہونے کے وقت اللّٰہُ اَکبَرُ کہنا۔\n۷۔ رکوع سے اٹھتے ہوئے سَمِعَ اللّٰهُ لِمَنْ حَمِدَهٗ اور رَبَّنَا لَكَ الْحَمْدُ کہنا۔\n۸۔ رکوع میں سُبْحَانَ رَبِّيَ الْعَظِيْمِ کم از کم تین مرتبہ کہنا۔\n۹۔ سجدے میں کم از کم تین مرتبہ سُبْحَانَ رَبِّيَ الْاَعْلٰى کہنا۔\n۱۰۔ دونوں سجدوں کے درمیان اور التحیات کیلئے مردوں کو بائیں پاؤں پر بیٹھنا اور سیدھا پاؤں کھڑا کرنا اور عورتوں کو دونوں پاؤں دائیں طرف نکال کر کولہوں پر بیٹھنا۔\n۱۱۔ درود شریف پڑھنا۔\n۱۲۔ درود کے بعد دعا پڑھنا۔\n۱۳۔ سلام کے وقت دائیں بائیں منہ پھیرنا۔\n۱۴۔ سلام میں فرشتوں اور مقتدیوں اور نیک جنات جو حاضر ہوں ان کی نیت کرنا۔",
    translation: "These are Sunnats of Namaz:\n\n1. Men raise hands to ears during Takbeer, women to chest.\n2. Men fold hands below navel, women on chest.\n3. Recite Sana (Subhanaka Allahumma...)\n4. Recite full A'udhu billah.\n5. Recite full Bismillah.\n6. Say Allahu Akbar when transitioning between positions.\n7. Say Sami'Allahu liman hamidah and Rabbana lakal-hamd.\n8. Say Subhana Rabbiyal-Azeem at least 3 times in Ruku.\n9. Say Subhana Rabbiyal-A'la at least 3 times in Sajda.\n10. Men sit on left foot between Sajdas, women sit with feet to the right.\n11. Recite Durood Sharif.\n12. Recite Dua after Durood.\n13. Turn face right and left for Salam.\n14. In Salam, intend greeting angels, followers, and righteous Jinn present.",
  },
  {
    number: 5,
    nameAr: "نَمَاز کے مُسْتَحَبَّات",
    nameEn: "Mustahabbat (Recommended Acts) of Namaz",
    arabic: "",
    content: "۱۔ اگر چادر اوڑھے ہو تو کانوں تک ہاتھ اٹھانے کے لئے مردوں کو چادر سے ہاتھ نکالنا۔\n۲۔ جہاں تک ممکن ہو کھانسی کو روکنا۔\n۳۔ جمائی آئے تو منہ بند کرنا۔\n۴۔ کھڑے ہونے کی حالت میں سجدے کی جگہ اور رکوع میں قدموں پر اور سجدے میں ناک پر اور بیٹھے ہونے گود میں اور سلام کے وقت کندھوں پر نظر رکھنا۔",
    translation: "1. If wearing a shawl, take hands out to raise them to ears.\n2. Suppress coughing as much as possible.\n3. Close mouth if yawning.\n4. Look at the place of Sajda while standing, at feet during Ruku, at nose during Sajda, at lap while sitting, and at shoulders during Salam.",
  },
  {
    number: 6,
    nameAr: "مَکْرُوْہَاتِ نَمَاز",
    nameEn: "Makroohat (Disliked Acts) in Namaz",
    arabic: "",
    content: "یہ چیزیں نماز میں مکروہ ہیں:\n\n۱۔ کوکھ پر ہاتھ رکھنا\n۲۔ آستین سے باہر ہاتھ نکالے رکھنا\n۳۔ کپڑا سمیٹنا\n۴۔ جسم یا کپڑے سے کھیلنا\n۵۔ انگلیاں چٹخانا\n۶۔ دائیں یا بائیں گردن موڑنا\n۷۔ مرد کو جوڑا گوندھ کر نماز میں پڑھنا\n۸۔ انگڑائی لینا\n۹۔ کتے کی طرح بیٹھنا\n۱۰۔ مرد کو سجدے میں ہاتھ زمین پر بچھانا\n۱۱۔ سجدے میں (مردوں کیلئے) پیٹ کو رانوں سے ملانا\n۱۲۔ بغیر عذر کے چار زانو (آلتی پالتی مار کر) بیٹھنا\n۱۳۔ امام کا محراب کے اندر کھڑا ہونا\n۱۴۔ صف سے علیحدہ تنہا کھڑا ہونا\n۱۵۔ سامنے یا سر پر تصویر ہونا\n۱۶۔ تصویر والے کپڑے میں نماز پڑھنا\n۱۷۔ کندھوں پر چادر یا کوئی کپڑ لٹکانا\n۱۸۔ پیشاب یا پاخانہ یا زیادہ بھوک کا تقاضا ہوتے ہوئے نماز پڑھنا\n۱۹۔ سر کھول کر نماز پڑھنا - یہ کراہت کا حکم مردوں کا ہے عورت سر کھول کر نماز پڑھے گی تو نماز نہ ہوگی\n۲۰۔ آنکھیں بند کر کے نماز پڑھنا",
    translation: "Disliked acts in Namaz:\n\n1. Placing hands on waist\n2. Keeping hands outside sleeves\n3. Folding clothes\n4. Playing with body or clothes\n5. Cracking fingers\n6. Turning neck right or left\n7. Men tying hair in a bun for prayer\n8. Stretching/yawning\n9. Sitting like a dog\n10. Men placing forearms on ground in Sajda\n11. Men pressing stomach against thighs in Sajda\n12. Sitting cross-legged without excuse\n13. Imam standing inside the niche\n14. Standing alone separate from the row\n15. Having pictures in front or on head\n16. Praying in clothes with pictures\n17. Draping a shawl/cloth over shoulders\n18. Praying while needing to use restroom or very hungry\n19. Men praying bareheaded (women: prayer invalid without head cover)\n20. Praying with eyes closed",
  },
];

export const sajdaSahw = [
  {
    number: 1,
    nameAr: "سَجْدَہ سَہو",
    nameEn: "Sajda Sahw (Prostration of Forgetfulness)",
    arabic: "",
    content: "کسی واجب کے چھوٹ جانے یا واجب یا فرض میں تاخیر یعنی دیر ہو جانے یا کسی فرض کو اس کی جگہ سے ہٹا کر پہلے کر دینے یا کسی فرض کو دو بارہ ادا کر دینے سے سجدہ سہو واجب ہو جاتا ہے اور اس سے بھول کی تلافی ہو جاتی ہے۔\n\nاگر قصداً ایسا کرے تو سجدہ سہو سے کام نہ چلے گا بلکہ نماز کا دہرانا لازم ہوگا۔ اور اگر کوئی فرض چھوٹ جائے تو اسکی تلافی سجدہ سہو سے نہ ہوگی۔\n\nطریقہ: آخری قعدے میں التحیات کے بعد دائیں طرف ایک سلام پھیر کر دو سجدے کریں۔ پھر التحیات، درود اور دعا پڑھ کر دونوں طرف سلام پھیریں۔",
    translation: "Sajda Sahw becomes obligatory when a Wajib act is missed, delayed, or a Fard is performed out of order or repeated. It compensates for forgetful mistakes.\n\nIf done deliberately, Sajda Sahw won't suffice — the entire prayer must be repeated. If a Fard is missed entirely, Sajda Sahw cannot compensate.\n\nMethod: In the final sitting, after At-Tahiyyat, turn right for one Salam, perform two Sajdas, then recite At-Tahiyyat, Durood, and Dua, and give Salam on both sides.",
  },
];

export const namazQasr = [
  {
    number: 1,
    nameAr: "نَمَازِ قَصْر",
    nameEn: "Qasr Prayer (Shortened Prayer for Travelers)",
    arabic: "",
    content: "جو شخص ۴۸ میل کے سفر کی نیت سے اپنے شہر یا قصبہ یا بستی سے نکل جائے اسکے لئے واپس آنے تک ظہر، عصر اور عشاء کی فرض نماز چار رکعت کے بجائے دو رکعت رہ جاتی ہے۔ ہاں اگر سفر میں کسی جگہ ۱۵ روز یا اس سے زیادہ ٹھہرنے کی نیت کر لے تو پوری چار رکعتیں پڑھنا فرض ہو جاتا ہے۔ ۴۸ میل کا سفر خواہ پیدل کرے خواہ ریل سے خواہ ہوائی جہاز سے خواہ اور کسی سواری سے سب کا یہی حکم ہے۔\n\nنیت نماز قصر: نیت کرتا ہوں دو رکعت نماز قصر کی وقت ظہر (یا عصر یا عشاء) کا واسطے اللہ تعالیٰ کے رخ میرا کعبہ شریف کی طرف اللہُ اَکبَرُ۔\n\nمسئلہ: قصر صرف ظہر، عصر یا عشاء کے فرضوں میں ہے مغرب اور فجر میں نہیں۔ اور فرضوں کے علاوہ اور کسی نماز میں بھی قصر نہیں ہے۔\n\nمسئلہ: مسافر آدمی اگر ایسے امام کے پیچھے نماز پڑھے جس کیلئے قصر جائز نہیں تو مسافر کو بھی اسکے ساتھ پوری نماز پڑھنی ہوگی۔",
    translation: "A person traveling 48 miles or more from their city reduces Zuhr, Asr, and Isha Fard prayers from 4 to 2 Rakaat until returning. If they intend to stay 15+ days at any place, they must pray full 4 Rakaat. This applies whether traveling by foot, train, airplane, or any vehicle.\n\nNiyyat for Qasr: I intend to pray 2 Rakaat Qasr prayer of Zuhr (or Asr/Isha), for the sake of Allah, facing the Ka'bah. Allahu Akbar.\n\nRuling: Qasr applies only to Zuhr, Asr, and Isha Fard — not Maghrib or Fajr. No Qasr for any prayer other than Fard.\n\nRuling: If a traveler prays behind an Imam for whom Qasr is not applicable, the traveler must also pray the full prayer.",
  },
];

export const eidainKaBiyan = [
  {
    number: 1,
    nameAr: "عِیدَین کے اَحکَام",
    nameEn: "Rules of Both Eids",
    arabic: "",
    content: "عیدین کے احکام:\n\n۱۔ غسل کرنا\n۲۔ مسواک کرنا\n۳۔ اپنے پاس جو کپڑے موجود ہوں ان میں سے سب سے اچھے کپڑے پہننا مگر مرد اور لڑکے ریشم کے کپڑے نہ پہنیں\n۴۔ خوشبو لگانا\n۵۔ عیدگاہ میں جو آبادی سے دور ہو عیدین کی نماز پڑھنا\n۶۔ عیدگاہ پیدل جانا\n۷۔ ایک راستے سے جانا اور دوسرے راستے سے واپس آنا\n۸۔ عید کی نماز سے پہلے گھر میں یا عیدگاہ میں نفل نماز نہ پڑھنا - گھر آکر پڑھے تو کوئی حرج نہیں\n۹۔ نماز عید الفطر سے پہلے کھجور یا کوئی میٹھی چیز کھانا\n۱۰۔ اگر صدقۂ فطر واجب ہو تو اس کو نماز سے پہلے ادا کرنا\n۱۱۔ عیدالاضحی ہو تو نماز کے بعد جلد سے جلد قربانی کرنا اور بہتر ہے کہ اس دن قربانی کے گوشت سے پہلے کچھ نہ کھائے",
    translation: "Rules of Both Eids:\n\n1. Take a bath\n2. Use Miswak\n3. Wear the best available clothes (men/boys should not wear silk)\n4. Apply perfume\n5. Pray Eid in an open field (Eidgah) away from town\n6. Walk to the Eidgah\n7. Go by one route and return by another\n8. Don't pray Nafl before Eid prayer at home or Eidgah\n9. Eat dates or something sweet before Eid-ul-Fitr prayer\n10. Pay Sadaqat-ul-Fitr before the prayer if obligatory\n11. On Eid-ul-Adha, sacrifice quickly after prayer; preferably don't eat before the Qurbani meat",
  },
  {
    number: 2,
    nameAr: "نَمَاز عِیدَین کَا طَرِیقَہ",
    nameEn: "Method of Eid Prayer",
    arabic: "",
    content: "نیت: نیت کرتا ہوں میں دو رکعت نماز واجب عید الفطر (یا عید الاضحیٰ) کی مع چھ تکبیروں کے پیچھے اس امام کے رخ میرا کعبہ شریف کی طرف۔\n\nنیت کے بعد امام و مقتدی کانوں تک ہاتھ اٹھائے ہوئے اللّٰهُ اَکبَرُ کہیں یہ تکبیر تحریمہ ہوگی۔\n\nاسکے بعد سُبْحَانَكَ اللّٰهُمَّ آخر تک پڑھیں۔\n\nسُبْحَانَكَ اللّٰهُمَّ کے بعد امام زائد تین تکبیریں کہے اور مقتدی بھی اسکے ساتھ تینوں تکبیریں کہتے جائیں زائد تکبیرات میں ہر مرتبہ مثل تکبیر تحریمہ کے دونوں کانوں تک ہاتھ اٹھائیں اور ہر تکبیر کے بعد اتنا توقف کریں کہ تین مرتبہ سُبْحَانَ اللّٰہِ کہہ سکیں۔\n\nتیسری تکبیر کے بعد ہاتھ نہ لٹکائیں بلکہ باندھ لیں اور امام اَعُوْذُ بِاللّٰهِ اور بِسْمِ اللّٰهِ (آخر تک) پڑھ کر سورہ فاتحہ اور کوئی سورت پڑھے، مقتدی خاموش کھڑے سنتے رہیں۔\n\nپھر رکوع سجدہ کر کے دوسری رکعت میں امام پہلے سورہ فاتحہ اور کوئی سورت پڑھے اسکے بعد تین تکبیریں امام اور مقتدی سب کہیں اور ہر بار کانوں تک ہاتھ اٹھا کر چھوڑ دیں۔ پھر چوتھی تکبیر ہاتھ اٹھائے بغیر کہتے ہوئے رکوع میں چلے جائیں اور روزانہ کی طرح باقی نماز پوری کریں۔\n\nمسئلہ: نماز عید الفطر اور عید الاضحیٰ مردوں پر واجب ہے اس کا چھوڑنا گناہ ہے۔ ہاں اگر شرعی سفر میں ہوں جس کا بیان نماز قصر کے بیان میں گزرا تو ان نمازوں میں شرکت نہ کرنے کی اجازت ہے۔\n\nمسئلہ: بہت سے لوگ عیدین کے دن خطبہ چھوڑ کر چل دیتے ہیں یا خطبے کے وقت بیٹھتے تو ہیں مگر باتیں کرتے رہتے ہیں یہ سب خلاف شرع ہے۔",
    translation: "Niyyat: I intend to pray 2 Rakaat Wajib of Eid-ul-Fitr (or Eid-ul-Adha) with 6 extra Takbeers, behind this Imam, facing the Ka'bah.\n\nAfter Niyyat, Imam and followers raise hands to ears saying Allahu Akbar (Takbeer Tahreema).\n\nThen recite Subhanaka Allahumma...\n\nAfter Subhanaka, Imam says 3 extra Takbeers. Followers repeat. Raise hands to ears each time. Pause between each Takbeer (enough to say Subhan-Allah 3 times).\n\nAfter 3rd Takbeer, fold hands (don't drop). Imam recites A'udhu Billah, Bismillah, Fatiha, and a Surah. Followers listen silently.\n\nAfter Ruku/Sajda, in 2nd Rakaat, Imam recites Fatiha and Surah first, then all say 3 Takbeers raising hands each time then dropping them. 4th Takbeer without raising hands, go into Ruku and complete normally.\n\nRuling: Eid prayer is Wajib on men. Missing it is sinful. Travelers (as in Qasr rules) are exempted.\n\nRuling: Leaving during or talking during the Khutbah is against Shariah.",
  },
  {
    number: 3,
    nameAr: "تَکبِیرِ تَشْرِیق",
    nameEn: "Takbeer Tashreeq",
    arabic: "اَللّٰهُ اَكْبَرُ اَللّٰهُ اَكْبَرُ لَآ اِلٰهَ اِلَّا اللّٰهُ وَاللّٰهُ اَكْبَرُ اَللّٰهُ اَكْبَرُ وَلِلّٰهِ الْحَمْدُ",
    content: "عید الفطر کی نماز کو جاتے ہوئے راستے میں آہستہ آواز سے تکبیر تشریق پڑھتے ہوئے جائیں اور عید الاضحیٰ کی نماز کو جاتے ہوئے بآواز بلند تکبیر تشریق کہتے جائیں۔\n\nمسئلہ: بقر عید کی نویں تاریخ کی نماز فجر سے لے کر تیرھویں تاریخ تک عصر تک ہر فرض نماز کے بعد بآواز بلند ایک بار تکبیر تشریق کہنا واجب ہے۔ امام بھول جائے تو مقتدی خود شروع کر دیں اس کا انتظار نہ کریں۔\n\nمسئلہ: عورت اس تکبیر کو آہستہ آواز سے پڑھے۔",
    translation: "Allah is the Greatest, Allah is the Greatest. There is no god but Allah, and Allah is the Greatest, Allah is the Greatest, and to Allah belongs all praise.\n\nRecite Takbeer Tashreeq softly while going for Eid-ul-Fitr, and loudly for Eid-ul-Adha.\n\nRuling: From Fajr of 9th Dhul-Hijjah to Asr of 13th, saying Takbeer Tashreeq once after every Fard prayer is Wajib. If Imam forgets, followers should start themselves.\n\nRuling: Women recite this Takbeer softly.",
  },
];

export const sajdaTilawat = [
  {
    number: 1,
    nameAr: "سَجْدَہ تِلَاوَت",
    nameEn: "Sajda Tilawat (Prostration of Recitation)",
    arabic: "",
    content: "قرآن شریف میں چودہ مقام ایسے ہیں جن کے پڑھنے یا سننے سے سجدہ کرنا واجب ہوتا ہے۔ اس کو سجدہ تلاوت کہتے ہیں۔ ان جگہوں پر قرآن شریف میں حاشیہ پر \"السجدة\" لکھا ہوا ہے۔ لیکن سرھنڈوں پارہ کے آخر میں جہاں \"السجدة\" لکھا ہے حنفی مذہب میں وہاں سجدہ نہیں ہے اور یہ جگہ چودہ کے علاوہ ہے۔\n\nسجدہ تلاوت ادا کرنے کا طریقہ یہ ہے کہ کھڑے ہو کر تکبیر کہتا ہوا اٹھ کھڑا ہو یہ افضل طریقہ ہے لیکن اگر بیٹھے بیٹھے ہی سجدے میں چلا گیا اور سجدے سے اٹھ کر بیٹھ گیا تب بھی سجدہ ادا ہو گیا۔ تلاوت کا صرف ایک ہی سجدہ کیا جاتا ہے نماز کی طرح دو سجدے نہیں ہوتے۔\n\nمسئلہ: اگر کسی نے سجدہ کی ایک آیت کو ایک ہی مجلس میں دو مرتبہ یا دو سے زیادہ مرتبہ پڑھایا سنا تو ایک سجدہ واجب ہوگا۔\n\nمسئلہ: سجدہ تلاوت کی ادائیگی کیلئے بدن، کپڑے، جگہ کا پاک ہونا، ستر ڈھانکنا، قبلہ رخ ہونا، سجدہ ادا کرنے کی نیت کرنا، باوضو ہونا شرط ہے۔\n\nمسئلہ: تلاوت کرتے کرتے سجدہ کی آیت چھوڑ جانا مکروہ ہے۔\n\nمسئلہ: تلاوت کرنے والا اگر سجدہ کی آیت کو آہستہ پڑھ دیوے تا کہ حاضرین تک آواز نہ پہنچے تو یہ مستحب ہے لیکن تراویح میں امام آیت سجدہ بھی زور سے پڑھے اور سب اس کے ساتھ سجدہ کریں۔\n\nتلاوت کرتے ہوئے جس وقت سجدہ کی آیت تلاوت کرے اسی وقت سجدہ کر لینا چاہئے۔ اگر کسی وجہ اس وقت سجدہ نہیں کیا تو معاف نہیں ہوا بعد میں ضرور کر لیوے۔ سجدہ تلاوت پڑھنے والے پر واجب ہوتا ہے اور جو سجدہ کی آیت سنے اس پر بھی۔",
    translation: "There are 14 places in the Quran where prostration becomes obligatory upon reading or hearing. This is called Sajda Tilawat. These places are marked with 'As-Sajdah' in the margin.\n\nMethod: Stand up, say Takbeer, and prostrate - this is the best way. But if you prostrate directly from sitting, it's also valid. Only one Sajda is performed (not two like in prayer).\n\nRuling: If one hears/recites the same Sajda verse multiple times in one sitting, only one Sajda is obligatory.\n\nRuling: Requirements: body, clothes, and place must be clean; cover Awrah; face Qibla; make intention; have Wudu.\n\nRuling: Skipping a Sajda verse during recitation is Makruh.\n\nRuling: Reciting the Sajda verse softly so listeners don't hear is Mustahab, but in Taraweeh the Imam should recite it aloud and all prostrate together.\n\nPerform the Sajda immediately when reciting the verse. If delayed, it must be made up later. It is Wajib on both the reciter and the listener.",
  },
];

export const taraweehKaBiyan = [
  {
    number: 1,
    nameAr: "تَرَاوِیح کَا بَیَان",
    nameEn: "Taraweeh Prayer",
    arabic: "",
    content: "مسئلہ: ماہ رمضان میں مردوں اور عورتوں کیلئے بیس رکعت تراویح بعد نماز عشاء ادا کرنا سنت مؤکدہ ہے۔\n\nحدیث: ارشاد فرمایا نبی کریم ﷺ نے کہ جس نے رمضان (کی راتوں) میں قیام کیا اسکے پچھلے گناہ معاف کر دیئے گئے۔\n\nمسئلہ: مردوں کو نماز تراویح با جماعت ادا کرنا سنت علی الکفایہ ہے۔ اگر تمام اہل محلہ الگ الگ تراویح پڑھ لیں گے اور جماعت بالکل نہ ہوگی تو سب گناہ گار ہوں گے۔ اور اگر با جماعت ادا ہو رہی ہے اور کسی نے تنہا پڑھ لی تو یہ شخص گناہ گار تو نہ ہوگا مگر فضیلت جماعت سے محروم ہوگا۔\n\nمسئلہ: نماز تراویح بیس رکعت دس سلاموں کے ساتھ ادا کریں اور ہر چار رکعت کے بعد تھوڑی دیر آرام کر لینا مستحب ہے۔\n\nمسئلہ: رمضان شریف کے پورے مہینے میں ایک مرتبہ قرآن شریف تراویح میں ختم کرنا سنت ہے۔\n\nمسئلہ: نابالغ کے پیچھے نماز تراویح پڑھنا درست نہیں ہے۔\n\nمسئلہ: بعض جگہ تراویح میں قرآن شریف ۱۵-۲۰ دن میں یا اس کے بعد مہینہ ختم ہونے سے پہلے ختم ہو جاتا ہے تو بہت سے لوگ اس کے بعد نماز تراویح چھوڑ دیتے ہیں یہ غلط ہے۔ کیونکہ قرآن شریف ختم کرنا مستقل ثواب کی چیز ہے اور پورے مہینے تراویح پڑھنا علیحدہ مستقل سنت ہے۔\n\nنیت تراویح: نیت کرتا ہوں میں دو رکعت نماز سنت تراویح کی، واسطے اللہ تعالیٰ کے، رخ میرا کعبہ کی طرف، پیچھے اس امام کے اللہُ اَکبَرُ۔",
    translation: "Ruling: In Ramadan, 20 Rakaat Taraweeh after Isha is Sunnah Muakkadah for men and women.\n\nHadith: The Prophet (PBUH) said: Whoever stands (in prayer) during Ramadan nights, their previous sins will be forgiven.\n\nRuling: Taraweeh with Jama'at is Sunnah Ala al-Kifayah for men. If everyone in the area prays individually and no congregation is formed, all are sinful. If congregation exists and someone prays alone, they're not sinful but miss the virtue.\n\nRuling: Pray 20 Rakaat with 10 Salams. Resting briefly after every 4 Rakaat is Mustahab.\n\nRuling: Completing Quran once in Taraweeh during Ramadan is Sunnah.\n\nRuling: Praying behind a minor (child) is not valid.\n\nRuling: Some places finish the Quran in 15-20 days and people stop Taraweeh after that — this is wrong. Quran completion has separate reward, and praying Taraweeh for the full month is a separate Sunnah.\n\nNiyyat: I intend to pray 2 Rakaat Sunnah Taraweeh, for the sake of Allah, facing the Ka'bah, behind this Imam. Allahu Akbar.",
  },
];

export const namazJanaza = [
  {
    number: 1,
    nameAr: "نَمَازِ جَنَازَہ",
    nameEn: "Janaza Prayer (Funeral Prayer)",
    arabic: "",
    content: "جنازے کی نماز فرض کفایہ ہے۔ اگر کچھ لوگ (بلکہ ایک مرد یا ایک عورت بھی) پڑھ لے تو فرض ادا ہو جاتا ہے۔ لیکن جس قدر بھی زیادہ آدمی ہوں اسی قدر میت کے حق میں اچھا ہے کیونکہ نہ معلوم کس کی دعا لگ جائے اور اس کی مغفرت ہو جائے۔\n\nحدیث: فرمایا رسول اللہ ﷺ نے کہ جو مسلمان مر جائے پھر کھڑے ہو کر چالیس آدمی اسکے جنازے کی نماز پڑھ لیں جو اللہ کے ساتھ کسی چیز کو شریک نہ کرتے ہوں تو اللہ ضرور ان کی سفارش میت کے حق میں قبول فرمائے گا۔\n\nمسئلہ: جنازے کی نماز میں صرف چار تکبیریں اور قیام یعنی کھڑا ہونا فرض ہے۔",
    translation: "Janaza prayer is Fard Kifayah. If some people (even one man or woman) pray it, the obligation is fulfilled. But the more people attend, the better for the deceased.\n\nHadith: The Prophet (PBUH) said: If a Muslim dies and 40 people who don't associate anything with Allah pray his Janaza, Allah will accept their intercession for the deceased.\n\nRuling: Only 4 Takbeers and standing (Qiyam) are Fard in Janaza prayer.",
  },
  {
    number: 2,
    nameAr: "طَرِیقَہ نَمَازِ جَنَازَہ",
    nameEn: "Method of Janaza Prayer",
    arabic: "",
    content: "طریقہ نماز جنازہ یہ ہے کہ میت کو آگے رکھ کر اس کے سینے کے مقابل امام کھڑا ہو اور نماز جنازہ کی نیت کرے۔\n\nنیت اس طرح ہے: نیت کرتا ہوں میں کہ نماز ادا کروں اس جنازے کی، تعریف واسطے اللہ تعالیٰ کے، دعا اس میت کیلئے پیچھے اس امام کے رخ میرا کعبہ شریف کی طرف۔\n\nنیت کر کے دونوں ہاتھ مثل تکبیر تحریمہ کے کانوں تک اٹھا کر ایک مرتبہ اللّٰهُ اَکبَرُ کہہ کر مثل عام نمازوں کے ہاتھ باندھ لیں۔\n\nپھر سُبْحَانَكَ اللّٰهُمَّ کہیں اس مرتبہ بھی ہاتھ نہ اٹھائیں۔ اس تکبیر کے بعد میت کیلئے دعاء کریں۔ اگر بالغ مرد یا عورت ہو تو یہ دعا پڑھیں:\n\nپھر چوتھی بار بغیر ہاتھ اٹھائے اللّٰهُ اَکبَرُ کہیں اور اس کے بعد دونوں طرف سلام پھیر دیں۔\n\nمسئلہ: جنازے کی نماز میں تکبیر کہتے ہوئے آسمان کی طرف منہ اٹھانا بے اصل ہے۔\n\nمسئلہ: اگر جوتے ناپاک ہوں تو ان کو پہن کر یا ان کے اوپر کھڑے ہو کر نماز جنازہ ادا نہ ہو گی۔ بہت سے لوگ اس کا خیال نہیں کرتے۔\n\nمسئلہ: جنازہ کی نماز میں مقتدیوں کی تین صفیں کر دینا مستحب ہے۔\n\nالحمد للہ نماز کا بیان ختم ہوا۔ اب چالیس دعائیں لکھی جاتی ہیں ان کو بھی یاد کریں اور موقعہ کے مطابق پڑھا کریں۔ یہ حضرت رسول مقبول ﷺ کی بتائی ہوئی ہیں۔",
    translation: "Method: Place the deceased in front, Imam stands facing the chest, and makes Niyyat for Janaza prayer.\n\nNiyyat: I intend to perform the prayer of this Janaza, praise for Allah, dua for this deceased, behind this Imam, facing the Ka'bah.\n\nRaise hands to ears like Takbeer Tahreema, say Allahu Akbar once, fold hands.\n\nRecite Subhanaka Allahumma... Then say second Allahu Akbar (without raising hands), recite Durood Ibrahim.\n\nThird Allahu Akbar (without raising hands), then make Dua for the deceased.\n\nFourth Allahu Akbar (without raising hands), then give Salam on both sides.\n\nRuling: Looking up at the sky during Takbeer in Janaza is baseless.\n\nRuling: Wearing impure shoes or standing on them invalidates the prayer.\n\nRuling: Making 3 rows of followers is Mustahab.",
  },
  {
    number: 3,
    nameAr: "دُعَا بَرَائے مَیِّتِ بَالِغ",
    nameEn: "Dua for Adult Deceased",
    arabic: "اَللّٰهُمَّ اغْفِرْ لِحَيِّنَا وَمَيِّتِنَا وَشَاهِدِنَا وَغَائِبِنَا وَصَغِيْرِنَا وَكَبِيْرِنَا وَذَكَرِنَا وَاُنْثَانَا\nاَللّٰهُمَّ مَنْ اَحْيَيْتَهٗ مِنَّا فَاَحْيِهٖ عَلَى الْاِسْلَامِ وَمَنْ تَوَفَّيْتَهٗ مِنَّا فَتَوَفَّهٗ عَلَى الْاِيْمَانِ",
    content: "اگر بالغ مرد یا عورت ہو تو تیسری تکبیر کے بعد یہ دعا پڑھیں۔\n\nترجمہ: اے اللہ! تو ہمارے زندوں کو بخش دے اور ہمارے مردوں کو اور ہمارے حاضروں کو اور ہمارے غائبوں کو اور ہمارے چھوٹوں کو اور ہمارے بڑوں کو اور ہمارے مردوں کو اور ہماری عورتوں کو۔ اے اللہ! ہم میں سے تو جسے زندہ رکھے اسے اسلام پر زندہ رکھ اور ہم میں سے تو جسے موت دے اسے ایمان پر موت دے۔",
    translation: "Recite this dua after the 3rd Takbeer for an adult male or female deceased.\n\nO Allah! Forgive our living and our dead, those present and those absent, our young and our old, our males and our females.\nO Allah! Whomever You keep alive among us, keep them alive upon Islam. And whomever You cause to die, let them die upon Iman (faith).",
  },
  {
    number: 4,
    nameAr: "دُعَا بَرَائے بَچّے (لَڑکَا)",
    nameEn: "Dua for Deceased Boy (Minor)",
    arabic: "اَللّٰهُمَّ اجْعَلْهُ لَنَا فَرَطًا وَاجْعَلْهُ لَنَا اَجْرًا وَّذُخْرًا وَاجْعَلْهُ لَنَا شَافِعًا وَّمُشَفَّعًا",
    content: "اگر میت نابالغ لڑکا ہو تو یہ دعا پڑھیں۔\n\nترجمہ: اے اللہ! اس بچے کو تو ہمارے لئے پہلے سے جا کر انتظام کرنے والا بنا اور اس کو ہمارے لئے اجر اور ذخیرہ اور سفارش کرنے والا اور سفارش منظور کیا ہوا بنا دے۔",
    translation: "Recite this dua if the deceased is a minor boy.\n\nO Allah! Make this child a forerunner for us (in Jannah), make him a reward and treasure for us, and make him an intercessor whose intercession is accepted.",
  },
  {
    number: 5,
    nameAr: "دُعَا بَرَائے بَچّی (لَڑکی)",
    nameEn: "Dua for Deceased Girl (Minor)",
    arabic: "اَللّٰهُمَّ اجْعَلْهَا لَنَا فَرَطًا وَاجْعَلْهَا لَنَا اَجْرًا وَّذُخْرًا وَاجْعَلْهَا لَنَا شَافِعَةً وَّمُشَفَّعَةً",
    content: "اگر میت نابالغ لڑکی ہو تو یہ دعا پڑھیں۔\n\nترجمہ: اے اللہ! اس بچی کو تو ہمارے لئے پہلے سے جا کر انتظام کرنے والی بنا اور اس کو ہمارے لئے اجر اور ذخیرہ اور سفارش کرنے والی اور سفارش منظوری کی ہوئی بنا۔",
    translation: "Recite this dua if the deceased is a minor girl.\n\nO Allah! Make this child a forerunner for us (in Jannah), make her a reward and treasure for us, and make her an intercessor whose intercession is accepted.",
  },
];
