export interface Theme {
  id: string;
  name: string;
  description: string;
  colors: {
    primary: string;
    secondary: string;
    accent: string;
    background: string;
    cardBg: string;
    text: string;
    textMuted: string;
    headerBg: string;
    headerText: string;
    gradient1?: string;
    gradient2?: string;
    gradient3?: string;
    glow?: string;
  };
  layout: 'grid' | 'list' | 'masonry' | 'cards' | 'minimal';
  heroStyle: 'full' | 'split' | 'minimal' | 'overlay' | 'none';
  cardStyle: 'rounded' | 'sharp' | 'floating' | 'bordered' | 'flat' | 'glass' | '3d';
  fontFamily: string;
  heroImage: string;
  heroGif?: string;
  patternBg?: string;
  animation?: 'none' | 'subtle' | 'moderate' | 'dynamic';
  effects?: {
    glassmorphism?: boolean;
    neonGlow?: boolean;
    particles?: boolean;
    gradientAnimation?: boolean;
    shadow3d?: boolean;
  };
}

export const themes: Record<string, Theme> = {
  classic: {
    id: 'classic',
    name: 'Classic Red',
    description: 'Bold red and black with a classic restaurant feel',
    colors: {
      primary: '#dc2626',
      secondary: '#1f2937',
      accent: '#fbbf24',
      background: '#0f0f0f',
      cardBg: '#1a1a1a',
      text: '#ffffff',
      textMuted: '#9ca3af',
      headerBg: '#dc2626',
      headerText: '#ffffff',
    },
    layout: 'grid',
    heroStyle: 'full',
    cardStyle: 'rounded',
    fontFamily: "'Poppins', sans-serif",
    heroImage: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1920&h=600&fit=crop',
    heroGif: '/classic-red-hero.gif',
  },
  
  modern: {
    id: 'modern',
    name: 'Modern Dark',
    description: 'Sleek dark theme with purple accents',
    colors: {
      primary: '#8b5cf6',
      secondary: '#1e1b4b',
      accent: '#c4b5fd',
      background: '#0c0a1d',
      cardBg: '#1e1b4b',
      text: '#f5f3ff',
      textMuted: '#a5b4fc',
      headerBg: 'linear-gradient(135deg, #8b5cf6 0%, #6366f1 100%)',
      headerText: '#ffffff',
    },
    layout: 'cards',
    heroStyle: 'overlay',
    cardStyle: 'floating',
    fontFamily: "'Inter', sans-serif",
    heroImage: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=1920&h=600&fit=crop',
  },
  
  rustic: {
    id: 'rustic',
    name: 'Rustic Wood',
    description: 'Warm brown tones with a cozy rustic feel',
    colors: {
      primary: '#b45309',
      secondary: '#78350f',
      accent: '#fcd34d',
      background: '#1c1410',
      cardBg: '#292018',
      text: '#fef3c7',
      textMuted: '#d6b36a',
      headerBg: '#78350f',
      headerText: '#fef3c7',
    },
    layout: 'list',
    heroStyle: 'split',
    cardStyle: 'bordered',
    fontFamily: "'Playfair Display', serif",
    heroImage: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1920&h=600&fit=crop',
    patternBg: 'url("data:image/svg+xml,%3Csvg width="60" height="60" viewBox="0 0 60 60" xmlns="http://www.w3.org/2000/svg"%3E%3Cpath d="M54.627 0l.83.828-1.415 1.415L51.8 0h2.827zM5.373 0l-.83.828L5.96 2.243 8.2 0H5.374zM48.97 0l3.657 3.657-1.414 1.414L46.143 0h2.828zM11.03 0L7.372 3.657 8.787 5.07 13.857 0H11.03zm32.284 0L49.8 6.485 48.384 7.9l-7.9-7.9h2.83zM16.686 0L10.2 6.485 11.616 7.9l7.9-7.9h-2.83zM22.344 0L13.858 8.485 15.272 9.9l9.9-9.9h-2.83zM32 0l-3.486 3.485-1.414-1.414L30.172 0H32z" fill="%23b45309" fill-opacity="0.05"/%3E%3C/svg%3E")',
  },
  
  ocean: {
    id: 'ocean',
    name: 'Ocean Blue',
    description: 'Cool blue tones inspired by the sea',
    colors: {
      primary: '#0891b2',
      secondary: '#164e63',
      accent: '#22d3ee',
      background: '#042f2e',
      cardBg: '#134e4a',
      text: '#f0fdfa',
      textMuted: '#5eead4',
      headerBg: 'linear-gradient(135deg, #0891b2 0%, #0e7490 100%)',
      headerText: '#ffffff',
    },
    layout: 'masonry',
    heroStyle: 'full',
    cardStyle: 'rounded',
    fontFamily: "'Montserrat', sans-serif",
    heroImage: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=1920&h=600&fit=crop',
  },
  
  neon: {
    id: 'neon',
    name: 'Neon Nights',
    description: 'Vibrant neon colors on dark background',
    colors: {
      primary: '#f43f5e',
      secondary: '#1f2937',
      accent: '#38bdf8',
      background: '#030712',
      cardBg: '#111827',
      text: '#f9fafb',
      textMuted: '#9ca3af',
      headerBg: '#030712',
      headerText: '#f43f5e',
    },
    layout: 'grid',
    heroStyle: 'minimal',
    cardStyle: 'sharp',
    fontFamily: "'Orbitron', sans-serif",
    heroImage: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=1920&h=600&fit=crop',
  },
  
  elegant: {
    id: 'elegant',
    name: 'Elegant Gold',
    description: 'Sophisticated black and gold design',
    colors: {
      primary: '#d4af37',
      secondary: '#1a1a1a',
      accent: '#f5e6c8',
      background: '#0a0a0a',
      cardBg: '#171717',
      text: '#fafafa',
      textMuted: '#a3a3a3',
      headerBg: '#0a0a0a',
      headerText: '#d4af37',
    },
    layout: 'cards',
    heroStyle: 'overlay',
    cardStyle: 'bordered',
    fontFamily: "'Cormorant Garamond', serif",
    heroImage: 'https://images.unsplash.com/photo-1544025162-d76978e8e5de?w=1920&h=600&fit=crop',
  },
  
  fresh: {
    id: 'fresh',
    name: 'Fresh Green',
    description: 'Natural green tones for a healthy vibe',
    colors: {
      primary: '#22c55e',
      secondary: '#166534',
      accent: '#86efac',
      background: '#052e16',
      cardBg: '#14532d',
      text: '#f0fdf4',
      textMuted: '#86efac',
      headerBg: '#166534',
      headerText: '#f0fdf4',
    },
    layout: 'list',
    heroStyle: 'split',
    cardStyle: 'floating',
    fontFamily: "'Nunito', sans-serif",
    heroImage: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=1920&h=600&fit=crop',
  },
  
  sunset: {
    id: 'sunset',
    name: 'Sunset Orange',
    description: 'Warm sunset colors with orange gradients',
    colors: {
      primary: '#f97316',
      secondary: '#c2410c',
      accent: '#fdba74',
      background: '#1c0f05',
      cardBg: '#431407',
      text: '#fff7ed',
      textMuted: '#fdba74',
      headerBg: 'linear-gradient(135deg, #f97316 0%, #ea580c 50%, #dc2626 100%)',
      headerText: '#ffffff',
    },
    layout: 'masonry',
    heroStyle: 'full',
    cardStyle: 'rounded',
    fontFamily: "'Quicksand', sans-serif",
    heroImage: 'https://images.unsplash.com/photo-1499028344343-cd173ffc68a9?w=1920&h=600&fit=crop',
  },
  
  midnight: {
    id: 'midnight',
    name: 'Midnight Blue',
    description: 'Deep blue with a luxurious midnight feel',
    colors: {
      primary: '#3b82f6',
      secondary: '#1e3a8a',
      accent: '#93c5fd',
      background: '#0c1222',
      cardBg: '#1e293b',
      text: '#f1f5f9',
      textMuted: '#94a3b8',
      headerBg: '#0c1222',
      headerText: '#3b82f6',
    },
    layout: 'grid',
    heroStyle: 'overlay',
    cardStyle: 'floating',
    fontFamily: "'Raleway', sans-serif",
    heroImage: 'https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=1920&h=600&fit=crop',
  },
  
  spicy: {
    id: 'spicy',
    name: 'Spicy Modern',
    description: 'Modern design with red, green, navy gradient - beautiful mixed colors',
    colors: {
      primary: '#dc2626',
      secondary: '#1e3a5f',
      accent: '#22c55e',
      background: '#f8fafc',
      cardBg: '#ffffff',
      text: '#1e293b',
      textMuted: '#64748b',
      headerBg: 'linear-gradient(135deg, #dc2626 0%, #1e3a5f 50%, #0f172a 100%)',
      headerText: '#ffffff',
    },
    layout: 'cards',
    heroStyle: 'none',
    cardStyle: 'rounded',
    fontFamily: "'Inter', sans-serif",
    heroImage: '',
  },

  tawa: {
    id: 'tawa',
    name: 'Tawa Clean',
    description: 'Clean white minimal design like NextOrder',
    colors: {
      primary: '#f97316',
      secondary: '#374151',
      accent: '#f97316',
      background: '#ffffff',
      cardBg: '#ffffff',
      text: '#1f2937',
      textMuted: '#6b7280',
      headerBg: '#ffffff',
      headerText: '#1f2937',
    },
    layout: 'cards',
    heroStyle: 'none',
    cardStyle: 'rounded',
    fontFamily: "'Inter', sans-serif",
    heroImage: '',
  },

  dhaba: {
    id: 'dhaba',
    name: 'Dhaba Traditional',
    description: 'Traditional Pakistani dhaba-style with warm earthy tones',
    colors: {
      primary: '#d97706',
      secondary: '#78350f',
      accent: '#fbbf24',
      background: '#fffbeb',
      cardBg: '#ffffff',
      text: '#1c1917',
      textMuted: '#78716c',
      headerBg: '#78350f',
      headerText: '#fef3c7',
    },
    layout: 'cards',
    heroStyle: 'none',
    cardStyle: 'rounded',
    fontFamily: "'Inter', sans-serif",
    heroImage: '',
  },

  burger: {
    id: 'burger',
    name: 'Burger Dramatic',
    description: 'Dark dramatic style with big images - perfect for burgers and grill menus',
    colors: {
      primary: '#eab308',
      secondary: '#1a1a1a',
      accent: '#fbbf24',
      background: '#1a1a1a',
      cardBg: '#2a2a2a',
      text: '#ffffff',
      textMuted: '#9ca3af',
      headerBg: '#0a0a0a',
      headerText: '#eab308',
    },
    layout: 'list',
    heroStyle: 'none',
    cardStyle: 'sharp',
    fontFamily: "'Poppins', sans-serif",
    heroImage: '',
  },

  afghanroyal: {
    id: 'afghanroyal',
    name: 'Afghan Royal',
    description: 'Elegant purple and gold theme with royal Afghan aesthetic',
    colors: {
      primary: '#7c3aed',
      secondary: '#4c1d95',
      accent: '#fbbf24',
      background: '#1e1b4b',
      cardBg: '#312e81',
      text: '#f5f3ff',
      textMuted: '#c4b5fd',
      headerBg: 'linear-gradient(135deg, #7c3aed 0%, #4c1d95 50%, #1e1b4b 100%)',
      headerText: '#fbbf24',
    },
    layout: 'cards',
    heroStyle: 'full',
    cardStyle: 'rounded',
    fontFamily: "'Playfair Display', serif",
    heroImage: '',
  },

  dixy: {
    id: 'dixy',
    name: 'Dixy Premium',
    description: 'Premium red and gold fried chicken theme',
    colors: {
      primary: '#dc2626',
      secondary: '#7f1d1d',
      accent: '#fbbf24',
      background: '#0f0f0f',
      cardBg: '#1a1a1a',
      text: '#ffffff',
      textMuted: '#9ca3af',
      headerBg: 'linear-gradient(135deg, #dc2626 0%, #991b1b 100%)',
      headerText: '#fbbf24',
    },
    layout: 'grid',
    heroStyle: 'full',
    cardStyle: 'rounded',
    fontFamily: "'Poppins', sans-serif",
    heroImage: '',
  },

  emparo: {
    id: 'emparo',
    name: 'Emparo Peri Peri',
    description: 'Fiery orange and black peri peri theme',
    colors: {
      primary: '#ea580c',
      secondary: '#1a1a1a',
      accent: '#fb923c',
      background: '#0c0a09',
      cardBg: '#1c1917',
      text: '#fafaf9',
      textMuted: '#a8a29e',
      headerBg: 'linear-gradient(135deg, #ea580c 0%, #c2410c 100%)',
      headerText: '#ffffff',
    },
    layout: 'cards',
    heroStyle: 'full',
    cardStyle: 'rounded',
    fontFamily: "'Montserrat', sans-serif",
    heroImage: '',
  },

  royal: {
    id: 'royal',
    name: 'Royal Premium',
    description: 'Luxurious purple and gold premium theme',
    colors: {
      primary: '#9333ea',
      secondary: '#581c87',
      accent: '#fbbf24',
      background: '#0f0518',
      cardBg: '#1e1033',
      text: '#faf5ff',
      textMuted: '#c084fc',
      headerBg: 'linear-gradient(135deg, #9333ea 0%, #7c3aed 50%, #6d28d9 100%)',
      headerText: '#fbbf24',
    },
    layout: 'cards',
    heroStyle: 'overlay',
    cardStyle: 'floating',
    fontFamily: "'Playfair Display', serif",
    heroImage: '',
  },
  tawagrill: {
    id: 'tawagrill',
    name: 'Tawa Grill Premium',
    description: 'Premium Pakistani & Afghani cuisine theme with charcoal, copper, and ember gradients',
    colors: {
      primary: '#c87533',
      secondary: '#2d2d2d',
      accent: '#e8a965',
      background: '#1a1a1a',
      cardBg: '#262626',
      text: '#f5f5f5',
      textMuted: '#a3a3a3',
      headerBg: 'linear-gradient(135deg, #1a1a1a 0%, #2d2d2d 50%, #1a1a1a 100%)',
      headerText: '#c87533',
    },
    layout: 'cards',
    heroStyle: 'full',
    cardStyle: 'rounded',
    fontFamily: "'Playfair Display', serif",
    heroImage: '',
  },

  // NEW BEAUTIFUL MULTI-COLOR THEMES

  royalgolddark: {
    id: 'royalgolddark',
    name: 'Royal Gold Dark',
    description: 'Luxurious black & gold with 9 color shades - elegant 3D modern classic',
    colors: {
      primary: '#d4af37',
      secondary: '#0d0d0d',
      accent: '#ffd700',
      background: '#050505',
      cardBg: '#0f0f0f',
      text: '#f5f5f5',
      textMuted: '#b8860b',
      headerBg: 'linear-gradient(135deg, #0d0d0d 0%, #1a1a1a 20%, #d4af37 40%, #ffd700 50%, #d4af37 60%, #1a1a1a 80%, #0d0d0d 100%)',
      headerText: '#ffd700',
      gradient1: '#d4af37',
      gradient2: '#8b6914',
      gradient3: '#ffd700',
      glow: '#d4af37',
    },
    layout: 'cards',
    heroStyle: 'overlay',
    cardStyle: 'glass',
    fontFamily: "'Playfair Display', serif",
    heroImage: '',
    animation: 'dynamic',
    effects: {
      glassmorphism: true,
      neonGlow: true,
      gradientAnimation: true,
      shadow3d: true,
    },
  },

  cosmicgalaxy: {
    id: 'cosmicgalaxy',
    name: 'Cosmic Galaxy',
    description: 'Deep space purple, pink, blue, cyan gradient - 9 cosmic colors with 3D glow effects',
    colors: {
      primary: '#8b5cf6',
      secondary: '#1e1b4b',
      accent: '#ec4899',
      background: '#030014',
      cardBg: '#0f0a2e',
      text: '#f5f3ff',
      textMuted: '#a78bfa',
      headerBg: 'linear-gradient(135deg, #030014 0%, #1e1b4b 15%, #4c1d95 30%, #7c3aed 45%, #ec4899 55%, #f472b6 65%, #06b6d4 80%, #1e1b4b 100%)',
      headerText: '#f5f3ff',
      gradient1: '#8b5cf6',
      gradient2: '#ec4899',
      gradient3: '#06b6d4',
      glow: '#a855f7',
    },
    layout: 'cards',
    heroStyle: 'full',
    cardStyle: '3d',
    fontFamily: "'Orbitron', sans-serif",
    heroImage: '',
    animation: 'dynamic',
    effects: {
      glassmorphism: true,
      neonGlow: true,
      particles: true,
      gradientAnimation: true,
      shadow3d: true,
    },
  },

  cherryblossom: {
    id: 'cherryblossom',
    name: 'Cherry Blossom',
    description: 'Elegant pink, rose gold, cream, burgundy - 8 beautiful feminine colors with soft animations',
    colors: {
      primary: '#f472b6',
      secondary: '#831843',
      accent: '#fbbf24',
      background: '#1a0a12',
      cardBg: '#2d1320',
      text: '#fdf2f8',
      textMuted: '#f9a8d4',
      headerBg: 'linear-gradient(135deg, #1a0a12 0%, #831843 20%, #be185d 35%, #f472b6 50%, #fbbf24 65%, #f9a8d4 80%, #fdf2f8 100%)',
      headerText: '#fbbf24',
      gradient1: '#f472b6',
      gradient2: '#be185d',
      gradient3: '#fbbf24',
      glow: '#f472b6',
    },
    layout: 'cards',
    heroStyle: 'overlay',
    cardStyle: 'glass',
    fontFamily: "'Playfair Display', serif",
    heroImage: '',
    animation: 'moderate',
    effects: {
      glassmorphism: true,
      gradientAnimation: true,
      shadow3d: true,
    },
  },

  emeraldluxury: {
    id: 'emeraldluxury',
    name: 'Emerald Luxury',
    description: 'Deep emerald green with gold accents - 9 rich jewel tones with 3D depth',
    colors: {
      primary: '#10b981',
      secondary: '#064e3b',
      accent: '#fbbf24',
      background: '#021a14',
      cardBg: '#052e21',
      text: '#ecfdf5',
      textMuted: '#6ee7b7',
      headerBg: 'linear-gradient(135deg, #021a14 0%, #064e3b 20%, #047857 35%, #10b981 45%, #fbbf24 55%, #d4af37 65%, #10b981 80%, #064e3b 100%)',
      headerText: '#fbbf24',
      gradient1: '#10b981',
      gradient2: '#047857',
      gradient3: '#fbbf24',
      glow: '#34d399',
    },
    layout: 'cards',
    heroStyle: 'full',
    cardStyle: '3d',
    fontFamily: "'Cormorant Garamond', serif",
    heroImage: '',
    animation: 'moderate',
    effects: {
      glassmorphism: true,
      neonGlow: true,
      shadow3d: true,
    },
  },

  sapphirenight: {
    id: 'sapphirenight',
    name: 'Sapphire Night',
    description: 'Deep sapphire blue with cyan and gold - 10 stunning night colors with glow effects',
    colors: {
      primary: '#3b82f6',
      secondary: '#1e3a8a',
      accent: '#fbbf24',
      background: '#020617',
      cardBg: '#0c1b3d',
      text: '#f1f5f9',
      textMuted: '#60a5fa',
      headerBg: 'linear-gradient(135deg, #020617 0%, #1e3a8a 15%, #1d4ed8 30%, #3b82f6 40%, #06b6d4 50%, #22d3ee 55%, #fbbf24 65%, #3b82f6 80%, #1e3a8a 100%)',
      headerText: '#fbbf24',
      gradient1: '#3b82f6',
      gradient2: '#06b6d4',
      gradient3: '#fbbf24',
      glow: '#60a5fa',
    },
    layout: 'cards',
    heroStyle: 'overlay',
    cardStyle: 'glass',
    fontFamily: "'Montserrat', sans-serif",
    heroImage: '',
    animation: 'dynamic',
    effects: {
      glassmorphism: true,
      neonGlow: true,
      particles: true,
      gradientAnimation: true,
      shadow3d: true,
    },
  },

  volcanicfire: {
    id: 'volcanicfire',
    name: 'Volcanic Fire',
    description: 'Intense red, orange, gold, black lava gradient - 9 fiery colors with dramatic 3D effects',
    colors: {
      primary: '#dc2626',
      secondary: '#450a0a',
      accent: '#fbbf24',
      background: '#0a0000',
      cardBg: '#1a0505',
      text: '#fef2f2',
      textMuted: '#f87171',
      headerBg: 'linear-gradient(135deg, #0a0000 0%, #450a0a 15%, #b91c1c 30%, #dc2626 40%, #ea580c 50%, #f97316 60%, #fbbf24 70%, #dc2626 85%, #450a0a 100%)',
      headerText: '#fbbf24',
      gradient1: '#dc2626',
      gradient2: '#ea580c',
      gradient3: '#fbbf24',
      glow: '#ef4444',
    },
    layout: 'cards',
    heroStyle: 'full',
    cardStyle: '3d',
    fontFamily: "'Poppins', sans-serif",
    heroImage: '',
    animation: 'dynamic',
    effects: {
      neonGlow: true,
      gradientAnimation: true,
      shadow3d: true,
    },
  },

  auroraborealis: {
    id: 'auroraborealis',
    name: 'Aurora Borealis',
    description: 'Northern lights inspired - green, blue, purple, teal gradient - 10 magical aurora colors',
    colors: {
      primary: '#22c55e',
      secondary: '#042f2e',
      accent: '#a855f7',
      background: '#020a09',
      cardBg: '#0a2520',
      text: '#f0fdf4',
      textMuted: '#4ade80',
      headerBg: 'linear-gradient(135deg, #020a09 0%, #042f2e 10%, #115e59 20%, #22c55e 35%, #14b8a6 45%, #06b6d4 55%, #6366f1 70%, #a855f7 80%, #6366f1 90%, #042f2e 100%)',
      headerText: '#f0fdf4',
      gradient1: '#22c55e',
      gradient2: '#06b6d4',
      gradient3: '#a855f7',
      glow: '#4ade80',
    },
    layout: 'cards',
    heroStyle: 'full',
    cardStyle: 'glass',
    fontFamily: "'Quicksand', sans-serif",
    heroImage: '',
    animation: 'dynamic',
    effects: {
      glassmorphism: true,
      neonGlow: true,
      particles: true,
      gradientAnimation: true,
      shadow3d: true,
    },
  },

  champagnerose: {
    id: 'champagnerose',
    name: 'Champagne Rose',
    description: 'Rose gold, champagne, cream, blush pink - 8 elegant luxury colors with soft glow',
    colors: {
      primary: '#e8b4b8',
      secondary: '#3d2a2c',
      accent: '#d4af37',
      background: '#1a1315',
      cardBg: '#2d2022',
      text: '#fdf4f5',
      textMuted: '#dda0a5',
      headerBg: 'linear-gradient(135deg, #1a1315 0%, #3d2a2c 20%, #8b5a5a 35%, #e8b4b8 45%, #d4af37 55%, #e8b4b8 65%, #fdf4f5 80%, #e8b4b8 100%)',
      headerText: '#d4af37',
      gradient1: '#e8b4b8',
      gradient2: '#d4af37',
      gradient3: '#fdf4f5',
      glow: '#e8b4b8',
    },
    layout: 'cards',
    heroStyle: 'overlay',
    cardStyle: 'glass',
    fontFamily: "'Cormorant Garamond', serif",
    heroImage: '',
    animation: 'subtle',
    effects: {
      glassmorphism: true,
      gradientAnimation: true,
    },
  },

  midnightluxe: {
    id: 'midnightluxe',
    name: 'Midnight Luxe',
    description: 'Deep purple, indigo, gold, black - 9 ultra-luxurious dark colors with premium 3D effects',
    colors: {
      primary: '#a855f7',
      secondary: '#2e1065',
      accent: '#fbbf24',
      background: '#0a0118',
      cardBg: '#1a0a2e',
      text: '#faf5ff',
      textMuted: '#c084fc',
      headerBg: 'linear-gradient(135deg, #0a0118 0%, #2e1065 15%, #581c87 30%, #7c3aed 40%, #a855f7 50%, #fbbf24 55%, #d4af37 60%, #a855f7 75%, #2e1065 100%)',
      headerText: '#fbbf24',
      gradient1: '#a855f7',
      gradient2: '#7c3aed',
      gradient3: '#fbbf24',
      glow: '#c084fc',
    },
    layout: 'cards',
    heroStyle: 'full',
    cardStyle: '3d',
    fontFamily: "'Playfair Display', serif",
    heroImage: '',
    animation: 'dynamic',
    effects: {
      glassmorphism: true,
      neonGlow: true,
      gradientAnimation: true,
      shadow3d: true,
    },
  },

  diamondelite: {
    id: 'diamondelite',
    name: 'Diamond Elite',
    description: 'Platinum silver, white, ice blue, crystal - 9 premium diamond colors with sparkling effects',
    colors: {
      primary: '#e5e7eb',
      secondary: '#1f2937',
      accent: '#60a5fa',
      background: '#0f1318',
      cardBg: '#1a1f26',
      text: '#f9fafb',
      textMuted: '#9ca3af',
      headerBg: 'linear-gradient(135deg, #0f1318 0%, #1f2937 15%, #374151 30%, #6b7280 40%, #e5e7eb 50%, #60a5fa 55%, #38bdf8 60%, #e5e7eb 75%, #1f2937 100%)',
      headerText: '#f9fafb',
      gradient1: '#e5e7eb',
      gradient2: '#60a5fa',
      gradient3: '#38bdf8',
      glow: '#e5e7eb',
    },
    layout: 'cards',
    heroStyle: 'overlay',
    cardStyle: 'glass',
    fontFamily: "'Montserrat', sans-serif",
    heroImage: '',
    animation: 'moderate',
    effects: {
      glassmorphism: true,
      neonGlow: true,
      shadow3d: true,
    },
  },

  'mujeeb-sweets': {
    id: 'mujeeb-sweets',
    name: 'Mujeeb Sweets Premium',
    description: 'Luxurious purple and gold sweets & bakery theme with no white pages - fully dark',
    colors: {
      primary: '#9B4DCA',
      secondary: '#1E0A3C',
      accent: '#F59E0B',
      background: '#0F0520',
      cardBg: '#1E0A3C',
      text: '#F5E6FF',
      textMuted: '#C4A7E7',
      headerBg: 'linear-gradient(135deg, #4A0080 0%, #7C3AED 30%, #9B4DCA 50%, #7C3AED 70%, #4A0080 100%)',
      headerText: '#F5E6FF',
      gradient1: '#9B4DCA',
      gradient2: '#7C3AED',
      gradient3: '#F59E0B',
      glow: '#C084FC',
    },
    layout: 'cards',
    heroStyle: 'full',
    cardStyle: 'glass',
    fontFamily: "'Playfair Display', serif",
    heroImage: '',
    animation: 'moderate',
    effects: {
      glassmorphism: true,
      neonGlow: true,
      gradientAnimation: true,
      shadow3d: true,
    },
  },
};

export const themeList = Object.values(themes);

export function getTheme(themeKey: string): Theme {
  return themes[themeKey] || themes.classic;
}
